--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5 (Debian 17.5-1.pgdg120+1)
-- Dumped by pg_dump version 17.5 (Debian 17.5-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: bio_open_lab_unisalentometadata; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.bio_open_lab_unisalentometadata (
    id bigint NOT NULL,
    device_name character varying(255),
    formatted_voltage character varying(50),
    exposure_s double precision,
    acquisition_date date,
    acquisition_time double precision,
    formatted_indicated_mag character varying(50),
    pixel_size_um jsonb,
    pixel_depth integer,
    stage_alpha character varying(50),
    stage_beta character varying(50),
    stage_x character varying(50),
    stage_y character varying(50),
    stage_z character varying(50),
    active_size_pixels jsonb,
    sample_id character varying(50),
    metadata_id character varying(64) NOT NULL
);


ALTER TABLE public.bio_open_lab_unisalentometadata OWNER TO decos;

--
-- Name: PRP_CDM_app_bio_open_lab_unisalentometadata_id_seq; Type: SEQUENCE; Schema: public; Owner: decos
--

ALTER TABLE public.bio_open_lab_unisalentometadata ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PRP_CDM_app_bio_open_lab_unisalentometadata_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: administration; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.administration (
    sr_id character varying(50) NOT NULL,
    lab_id character varying(50) NOT NULL,
    dmptitle character varying(128) NOT NULL,
    user_id character varying(50) NOT NULL,
    email character varying(128) NOT NULL,
    affiliation character varying(128) NOT NULL,
    experimentabstract text NOT NULL
);


ALTER TABLE public.administration OWNER TO decos;

--
-- Name: bioopenlabunisalento_samples; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.bioopenlabunisalento_samples (
    samples_ptr_id character varying(50) NOT NULL,
    sample_name character varying(255) NOT NULL,
    sample_producer character varying(255) NOT NULL,
    affiliation character varying(255) NOT NULL,
    sample_purpose character varying NOT NULL,
    sample_type character varying NOT NULL,
    component_name character varying(255) NOT NULL,
    component_chemical_formula character varying(255) NOT NULL,
    sheet character varying NOT NULL,
    layer character varying NOT NULL,
    colloidal_solution character varying(255) NOT NULL,
    sample_expiration_date date,
    additional_filename character varying(100) NOT NULL
);


ALTER TABLE public.bioopenlabunisalento_samples OWNER TO decos;

--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO decos;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: decos
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: experiment_dmp; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.experiment_dmp (
    experiment_dmp_id character varying(50) NOT NULL,
    affiliated_institutions text NOT NULL,
    collaborators_roles text,
    estimated_costs text,
    ethics_approvals text,
    experiment_title character varying(255) NOT NULL,
    funding_programme character varying(255),
    grant_number character varying(100),
    infrastructure_support text,
    plan_creation_date date NOT NULL,
    principal_investigator character varying(255) NOT NULL,
    project_acronym character varying(100),
    roles_responsibilities text,
    public_dataset text
);


ALTER TABLE public.experiment_dmp OWNER TO decos;

--
-- Name: experiment_dmp_x_instrument; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.experiment_dmp_x_instrument (
    x_id character varying(50) NOT NULL,
    experiment_dmp_id character varying(50) NOT NULL,
    instruments_id character varying(50) NOT NULL
);


ALTER TABLE public.experiment_dmp_x_instrument OWNER TO decos;

--
-- Name: experiment_dmp_x_lab; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.experiment_dmp_x_lab (
    x_id character varying(50) NOT NULL,
    experiment_dmp_id character varying(50) NOT NULL,
    lab_id character varying(50) NOT NULL
);


ALTER TABLE public.experiment_dmp_x_lab OWNER TO decos;

--
-- Name: experiment_dmp_x_sample; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.experiment_dmp_x_sample (
    x_id character varying(50) NOT NULL,
    experiment_dmp_id character varying(50) NOT NULL,
    samples_id character varying(50) NOT NULL
);


ALTER TABLE public.experiment_dmp_x_sample OWNER TO decos;

--
-- Name: instrument_x_technique; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.instrument_x_technique (
    x_id character varying(50) NOT NULL,
    instrument_id_id character varying(50) NOT NULL,
    technique_id_id character varying(50) NOT NULL
);


ALTER TABLE public.instrument_x_technique OWNER TO decos;

--
-- Name: instruments; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.instruments (
    instrument_id character varying(50) NOT NULL,
    vendor character varying(50) NOT NULL,
    model character varying(50) NOT NULL,
    description character varying(50) NOT NULL
);


ALTER TABLE public.instruments OWNER TO decos;

--
-- Name: lab_x_instrument; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.lab_x_instrument (
    id bigint NOT NULL,
    instrument_id_id character varying(50) NOT NULL,
    lab_id_id character varying(50) NOT NULL
);


ALTER TABLE public.lab_x_instrument OWNER TO decos;

--
-- Name: lab_x_instrument_id_seq; Type: SEQUENCE; Schema: public; Owner: decos
--

ALTER TABLE public.lab_x_instrument ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lab_x_instrument_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: labdmp; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.labdmp (
    lab_id character varying(128) NOT NULL,
    user_id character varying(50) NOT NULL,
    instrument_metadata_collection character varying(128) NOT NULL,
    additional_enotebook_open_collection character varying(128) NOT NULL,
    sample_standard character varying(128) NOT NULL,
    metadata_schema_defined character varying NOT NULL,
    backup_policy_published_data character varying NOT NULL,
    backup_policy_unplublished_data character varying NOT NULL,
    data_curator character varying(128) NOT NULL
);


ALTER TABLE public.labdmp OWNER TO decos;

--
-- Name: laboratories; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.laboratories (
    lab_id character varying(50) NOT NULL,
    description character varying(50) NOT NULL
);


ALTER TABLE public.laboratories OWNER TO decos;

--
-- Name: lage_samples; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.lage_samples (
    samples_ptr_id character varying(50) NOT NULL,
    type character varying NOT NULL,
    is_volume_in_ul character varying NOT NULL,
    is_buffer_used character varying NOT NULL,
    is_quality character varying NOT NULL,
    sample_date_of_delivery date NOT NULL,
    sample_back boolean NOT NULL,
    reagents_provided_by_client boolean NOT NULL,
    reagents_date_of_delivery date,
    sample_sheet_filename character varying(100) NOT NULL,
    additional_filename character varying(100) NOT NULL
);


ALTER TABLE public.lage_samples OWNER TO decos;

--
-- Name: lame_samples; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.lame_samples (
    samples_ptr_id character varying(50) NOT NULL,
    chemical_formula character varying NOT NULL,
    elements_list character varying NOT NULL,
    sample_date_of_delivery date NOT NULL,
    sample_back boolean NOT NULL,
    sample_sheet_filename character varying(100) NOT NULL,
    additional_filename character varying(100) NOT NULL
);


ALTER TABLE public.lame_samples OWNER TO decos;

--
-- Name: proposals; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.proposals (
    proposal_id character varying(50) NOT NULL,
    proposal_status character varying NOT NULL,
    proposal_feasibility character varying NOT NULL,
    proposal_date date NOT NULL,
    proposal_filename character varying(100) NOT NULL,
    user_id_id character varying(50) NOT NULL
);


ALTER TABLE public.proposals OWNER TO decos;

--
-- Name: questions; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.questions (
    question_id character varying(50) NOT NULL,
    question text NOT NULL,
    answer text NOT NULL,
    sample_id_id character varying(50) NOT NULL
);


ALTER TABLE public.questions OWNER TO decos;

--
-- Name: result_x_experiment_dmp; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.result_x_experiment_dmp (
    x_id character varying(50) NOT NULL,
    experiment_dmp_id character varying(50) NOT NULL,
    result_id character varying(50) NOT NULL
);


ALTER TABLE public.result_x_experiment_dmp OWNER TO decos;

--
-- Name: result_x_laboratories; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.result_x_laboratories (
    x_id character varying(50) NOT NULL,
    lab_id character varying(50) NOT NULL,
    result_id character varying(50) NOT NULL
);


ALTER TABLE public.result_x_laboratories OWNER TO decos;

--
-- Name: results; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.results (
    result_id character varying(50) NOT NULL,
    main_repository character varying(2048) NOT NULL,
    article_doi character varying(256) NOT NULL,
    authors text NOT NULL,
    journal_name character varying(256) NOT NULL,
    publication_title character varying(512) NOT NULL,
    publication_year integer,
    clear_data_provenance boolean NOT NULL,
    licence_scientific_documents boolean NOT NULL,
    open_access_journal_publication boolean NOT NULL,
    open_data_licence character varying NOT NULL,
    open_trusted_repo_published_data boolean NOT NULL,
    raw_data_storage_location character varying NOT NULL,
    raw_data_storage_time_retention character varying NOT NULL,
    related_data_open boolean NOT NULL,
    CONSTRAINT results_publication_year_check CHECK ((publication_year >= 0))
);


ALTER TABLE public.results OWNER TO decos;

--
-- Name: samples; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.samples (
    sample_id character varying(50) NOT NULL,
    sample_short_description character varying(64) NOT NULL,
    sample_description text NOT NULL,
    sample_feasibility character varying NOT NULL,
    sample_status character varying NOT NULL,
    sample_location character varying,
    lab_id_id character varying(50) NOT NULL,
    sr_id_id character varying(50),
    sensible_data boolean NOT NULL
);


ALTER TABLE public.samples OWNER TO decos;

--
-- Name: service_requests; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.service_requests (
    sr_id character varying(50) NOT NULL,
    sr_status character varying NOT NULL,
    exp_description text NOT NULL,
    output_delivery_date date NOT NULL,
    lab_id_id character varying(50) NOT NULL,
    proposal_id_id character varying(50) NOT NULL
);


ALTER TABLE public.service_requests OWNER TO decos;

--
-- Name: steps; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.steps (
    step_id character varying(50) NOT NULL,
    assigned_uoa integer NOT NULL,
    performed_uoa integer NOT NULL,
    eff_sample_date_of_delivery date NOT NULL,
    eff_reagents_date_of_delivery date NOT NULL,
    sample_quality character varying NOT NULL,
    sample_quality_description text NOT NULL,
    sample_quality_extra_budjet boolean NOT NULL,
    instrument_id_id character varying(50) NOT NULL,
    sample_id_id character varying(50) NOT NULL,
    technique_id_id character varying(50) NOT NULL
);


ALTER TABLE public.steps OWNER TO decos;

--
-- Name: techniques; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.techniques (
    technique_id character varying(50) NOT NULL,
    technique_name character varying(50) NOT NULL,
    description character varying(50) NOT NULL
);


ALTER TABLE public.techniques OWNER TO decos;

--
-- Name: users; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.users (
    user_id character varying(50) NOT NULL,
    name_surname character varying(50) NOT NULL,
    email character varying(128) NOT NULL,
    affiliation character varying(128) NOT NULL,
    gender character varying NOT NULL,
    legal_status character varying,
    research_role character varying NOT NULL
);


ALTER TABLE public.users OWNER TO decos;

--
-- Name: bio_open_lab_unisalentometadata PRP_CDM_app_bio_open_lab_unisalentometadata_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.bio_open_lab_unisalentometadata
    ADD CONSTRAINT "PRP_CDM_app_bio_open_lab_unisalentometadata_pkey" PRIMARY KEY (id);


--
-- Name: administration administration_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.administration
    ADD CONSTRAINT administration_pkey PRIMARY KEY (sr_id);


--
-- Name: bio_open_lab_unisalentometadata bio_open_lab_unisalentometadata_metadata_id_key; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.bio_open_lab_unisalentometadata
    ADD CONSTRAINT bio_open_lab_unisalentometadata_metadata_id_key UNIQUE (metadata_id);


--
-- Name: bioopenlabunisalento_samples bioopenlabunisalento_samples_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.bioopenlabunisalento_samples
    ADD CONSTRAINT bioopenlabunisalento_samples_pkey PRIMARY KEY (samples_ptr_id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: experiment_dmp experiment_dmp_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.experiment_dmp
    ADD CONSTRAINT experiment_dmp_pkey PRIMARY KEY (experiment_dmp_id);


--
-- Name: experiment_dmp_x_instrument experiment_dmp_x_instrument_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.experiment_dmp_x_instrument
    ADD CONSTRAINT experiment_dmp_x_instrument_pkey PRIMARY KEY (x_id);


--
-- Name: experiment_dmp_x_lab experiment_dmp_x_lab_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.experiment_dmp_x_lab
    ADD CONSTRAINT experiment_dmp_x_lab_pkey PRIMARY KEY (x_id);


--
-- Name: experiment_dmp_x_sample experiment_dmp_x_sample_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.experiment_dmp_x_sample
    ADD CONSTRAINT experiment_dmp_x_sample_pkey PRIMARY KEY (x_id);


--
-- Name: instrument_x_technique instrument_x_technique_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.instrument_x_technique
    ADD CONSTRAINT instrument_x_technique_pkey PRIMARY KEY (x_id);


--
-- Name: instruments instruments_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.instruments
    ADD CONSTRAINT instruments_pkey PRIMARY KEY (instrument_id);


--
-- Name: lab_x_instrument lab_x_instrument_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.lab_x_instrument
    ADD CONSTRAINT lab_x_instrument_pkey PRIMARY KEY (id);


--
-- Name: labdmp labdmp_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.labdmp
    ADD CONSTRAINT labdmp_pkey PRIMARY KEY (lab_id);


--
-- Name: laboratories laboratories_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.laboratories
    ADD CONSTRAINT laboratories_pkey PRIMARY KEY (lab_id);


--
-- Name: lage_samples lage_samples_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.lage_samples
    ADD CONSTRAINT lage_samples_pkey PRIMARY KEY (samples_ptr_id);


--
-- Name: lame_samples lame_samples_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.lame_samples
    ADD CONSTRAINT lame_samples_pkey PRIMARY KEY (samples_ptr_id);


--
-- Name: proposals proposals_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.proposals
    ADD CONSTRAINT proposals_pkey PRIMARY KEY (proposal_id);


--
-- Name: questions questions_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT questions_pkey PRIMARY KEY (question_id);


--
-- Name: result_x_experiment_dmp result_x_experiment_dmp_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.result_x_experiment_dmp
    ADD CONSTRAINT result_x_experiment_dmp_pkey PRIMARY KEY (x_id);


--
-- Name: result_x_laboratories result_x_laboratories_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.result_x_laboratories
    ADD CONSTRAINT result_x_laboratories_pkey PRIMARY KEY (x_id);


--
-- Name: results results_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.results
    ADD CONSTRAINT results_pkey PRIMARY KEY (result_id);


--
-- Name: samples samples_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.samples
    ADD CONSTRAINT samples_pkey PRIMARY KEY (sample_id);


--
-- Name: service_requests service_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.service_requests
    ADD CONSTRAINT service_requests_pkey PRIMARY KEY (sr_id);


--
-- Name: steps steps_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.steps
    ADD CONSTRAINT steps_pkey PRIMARY KEY (step_id);


--
-- Name: techniques techniques_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.techniques
    ADD CONSTRAINT techniques_pkey PRIMARY KEY (technique_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: administration_sr_id_44c4faf2_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX administration_sr_id_44c4faf2_like ON public.administration USING btree (sr_id varchar_pattern_ops);


--
-- Name: bio_open_lab_unisalentometadata_metadata_id_1a08b75a_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX bio_open_lab_unisalentometadata_metadata_id_1a08b75a_like ON public.bio_open_lab_unisalentometadata USING btree (metadata_id varchar_pattern_ops);


--
-- Name: bio_open_lab_unisalentometadata_sample_id_6363fc37; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX bio_open_lab_unisalentometadata_sample_id_6363fc37 ON public.bio_open_lab_unisalentometadata USING btree (sample_id);


--
-- Name: bio_open_lab_unisalentometadata_sample_id_6363fc37_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX bio_open_lab_unisalentometadata_sample_id_6363fc37_like ON public.bio_open_lab_unisalentometadata USING btree (sample_id varchar_pattern_ops);


--
-- Name: bioopenlabunisalento_samples_samples_ptr_id_44136c80_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX bioopenlabunisalento_samples_samples_ptr_id_44136c80_like ON public.bioopenlabunisalento_samples USING btree (samples_ptr_id varchar_pattern_ops);


--
-- Name: experiment_dmp_experiment_dmp_id_c66a5d55_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX experiment_dmp_experiment_dmp_id_c66a5d55_like ON public.experiment_dmp USING btree (experiment_dmp_id varchar_pattern_ops);


--
-- Name: experiment_dmp_x_instrument_experiment_dmp_id_82c1580a; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX experiment_dmp_x_instrument_experiment_dmp_id_82c1580a ON public.experiment_dmp_x_instrument USING btree (experiment_dmp_id);


--
-- Name: experiment_dmp_x_instrument_experiment_dmp_id_82c1580a_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX experiment_dmp_x_instrument_experiment_dmp_id_82c1580a_like ON public.experiment_dmp_x_instrument USING btree (experiment_dmp_id varchar_pattern_ops);


--
-- Name: experiment_dmp_x_instrument_instruments_id_96518eb5; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX experiment_dmp_x_instrument_instruments_id_96518eb5 ON public.experiment_dmp_x_instrument USING btree (instruments_id);


--
-- Name: experiment_dmp_x_instrument_instruments_id_96518eb5_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX experiment_dmp_x_instrument_instruments_id_96518eb5_like ON public.experiment_dmp_x_instrument USING btree (instruments_id varchar_pattern_ops);


--
-- Name: experiment_dmp_x_instrument_x_id_b73c03c1_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX experiment_dmp_x_instrument_x_id_b73c03c1_like ON public.experiment_dmp_x_instrument USING btree (x_id varchar_pattern_ops);


--
-- Name: experiment_dmp_x_lab_experiment_dmp_id_24bbc56b; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX experiment_dmp_x_lab_experiment_dmp_id_24bbc56b ON public.experiment_dmp_x_lab USING btree (experiment_dmp_id);


--
-- Name: experiment_dmp_x_lab_experiment_dmp_id_24bbc56b_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX experiment_dmp_x_lab_experiment_dmp_id_24bbc56b_like ON public.experiment_dmp_x_lab USING btree (experiment_dmp_id varchar_pattern_ops);


--
-- Name: experiment_dmp_x_lab_lab_id_eadcf955; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX experiment_dmp_x_lab_lab_id_eadcf955 ON public.experiment_dmp_x_lab USING btree (lab_id);


--
-- Name: experiment_dmp_x_lab_lab_id_eadcf955_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX experiment_dmp_x_lab_lab_id_eadcf955_like ON public.experiment_dmp_x_lab USING btree (lab_id varchar_pattern_ops);


--
-- Name: experiment_dmp_x_lab_x_id_ebef1838_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX experiment_dmp_x_lab_x_id_ebef1838_like ON public.experiment_dmp_x_lab USING btree (x_id varchar_pattern_ops);


--
-- Name: experiment_dmp_x_sample_experiment_dmp_id_7db23d1b; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX experiment_dmp_x_sample_experiment_dmp_id_7db23d1b ON public.experiment_dmp_x_sample USING btree (experiment_dmp_id);


--
-- Name: experiment_dmp_x_sample_experiment_dmp_id_7db23d1b_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX experiment_dmp_x_sample_experiment_dmp_id_7db23d1b_like ON public.experiment_dmp_x_sample USING btree (experiment_dmp_id varchar_pattern_ops);


--
-- Name: experiment_dmp_x_sample_samples_id_636b93ea; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX experiment_dmp_x_sample_samples_id_636b93ea ON public.experiment_dmp_x_sample USING btree (samples_id);


--
-- Name: experiment_dmp_x_sample_samples_id_636b93ea_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX experiment_dmp_x_sample_samples_id_636b93ea_like ON public.experiment_dmp_x_sample USING btree (samples_id varchar_pattern_ops);


--
-- Name: experiment_dmp_x_sample_x_id_7d559262_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX experiment_dmp_x_sample_x_id_7d559262_like ON public.experiment_dmp_x_sample USING btree (x_id varchar_pattern_ops);


--
-- Name: instrument_x_technique_instrument_id_id_2775fa5a; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX instrument_x_technique_instrument_id_id_2775fa5a ON public.instrument_x_technique USING btree (instrument_id_id);


--
-- Name: instrument_x_technique_instrument_id_id_2775fa5a_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX instrument_x_technique_instrument_id_id_2775fa5a_like ON public.instrument_x_technique USING btree (instrument_id_id varchar_pattern_ops);


--
-- Name: instrument_x_technique_technique_id_id_67a1725a; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX instrument_x_technique_technique_id_id_67a1725a ON public.instrument_x_technique USING btree (technique_id_id);


--
-- Name: instrument_x_technique_technique_id_id_67a1725a_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX instrument_x_technique_technique_id_id_67a1725a_like ON public.instrument_x_technique USING btree (technique_id_id varchar_pattern_ops);


--
-- Name: instrument_x_technique_x_id_09847299_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX instrument_x_technique_x_id_09847299_like ON public.instrument_x_technique USING btree (x_id varchar_pattern_ops);


--
-- Name: instruments_instrument_id_99cd1132_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX instruments_instrument_id_99cd1132_like ON public.instruments USING btree (instrument_id varchar_pattern_ops);


--
-- Name: lab_x_instrument_instrument_id_id_61b2ee3a; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX lab_x_instrument_instrument_id_id_61b2ee3a ON public.lab_x_instrument USING btree (instrument_id_id);


--
-- Name: lab_x_instrument_instrument_id_id_61b2ee3a_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX lab_x_instrument_instrument_id_id_61b2ee3a_like ON public.lab_x_instrument USING btree (instrument_id_id varchar_pattern_ops);


--
-- Name: lab_x_instrument_lab_id_id_cf79aee8; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX lab_x_instrument_lab_id_id_cf79aee8 ON public.lab_x_instrument USING btree (lab_id_id);


--
-- Name: lab_x_instrument_lab_id_id_cf79aee8_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX lab_x_instrument_lab_id_id_cf79aee8_like ON public.lab_x_instrument USING btree (lab_id_id varchar_pattern_ops);


--
-- Name: labdmp_lab_id_5ca421c0_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX labdmp_lab_id_5ca421c0_like ON public.labdmp USING btree (lab_id varchar_pattern_ops);


--
-- Name: laboratories_lab_id_226b791e_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX laboratories_lab_id_226b791e_like ON public.laboratories USING btree (lab_id varchar_pattern_ops);


--
-- Name: lage_samples_samples_ptr_id_ee82f820_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX lage_samples_samples_ptr_id_ee82f820_like ON public.lage_samples USING btree (samples_ptr_id varchar_pattern_ops);


--
-- Name: lame_samples_samples_ptr_id_d6261525_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX lame_samples_samples_ptr_id_d6261525_like ON public.lame_samples USING btree (samples_ptr_id varchar_pattern_ops);


--
-- Name: proposals_proposal_id_6eff373c_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX proposals_proposal_id_6eff373c_like ON public.proposals USING btree (proposal_id varchar_pattern_ops);


--
-- Name: proposals_user_id_id_10217a25; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX proposals_user_id_id_10217a25 ON public.proposals USING btree (user_id_id);


--
-- Name: proposals_user_id_id_10217a25_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX proposals_user_id_id_10217a25_like ON public.proposals USING btree (user_id_id varchar_pattern_ops);


--
-- Name: questions_question_id_243ed5e8_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX questions_question_id_243ed5e8_like ON public.questions USING btree (question_id varchar_pattern_ops);


--
-- Name: questions_sample_id_id_f5a232cc; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX questions_sample_id_id_f5a232cc ON public.questions USING btree (sample_id_id);


--
-- Name: questions_sample_id_id_f5a232cc_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX questions_sample_id_id_f5a232cc_like ON public.questions USING btree (sample_id_id varchar_pattern_ops);


--
-- Name: result_x_experiment_dmp_experiment_dmp_id_14ff90d9; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX result_x_experiment_dmp_experiment_dmp_id_14ff90d9 ON public.result_x_experiment_dmp USING btree (experiment_dmp_id);


--
-- Name: result_x_experiment_dmp_experiment_dmp_id_14ff90d9_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX result_x_experiment_dmp_experiment_dmp_id_14ff90d9_like ON public.result_x_experiment_dmp USING btree (experiment_dmp_id varchar_pattern_ops);


--
-- Name: result_x_experiment_dmp_result_id_3f62147c; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX result_x_experiment_dmp_result_id_3f62147c ON public.result_x_experiment_dmp USING btree (result_id);


--
-- Name: result_x_experiment_dmp_result_id_3f62147c_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX result_x_experiment_dmp_result_id_3f62147c_like ON public.result_x_experiment_dmp USING btree (result_id varchar_pattern_ops);


--
-- Name: result_x_experiment_dmp_x_id_136a460a_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX result_x_experiment_dmp_x_id_136a460a_like ON public.result_x_experiment_dmp USING btree (x_id varchar_pattern_ops);


--
-- Name: result_x_laboratories_lab_id_c0c876a7; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX result_x_laboratories_lab_id_c0c876a7 ON public.result_x_laboratories USING btree (lab_id);


--
-- Name: result_x_laboratories_lab_id_c0c876a7_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX result_x_laboratories_lab_id_c0c876a7_like ON public.result_x_laboratories USING btree (lab_id varchar_pattern_ops);


--
-- Name: result_x_laboratories_result_id_69dd30a6; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX result_x_laboratories_result_id_69dd30a6 ON public.result_x_laboratories USING btree (result_id);


--
-- Name: result_x_laboratories_result_id_69dd30a6_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX result_x_laboratories_result_id_69dd30a6_like ON public.result_x_laboratories USING btree (result_id varchar_pattern_ops);


--
-- Name: result_x_laboratories_x_id_35e3c5b1_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX result_x_laboratories_x_id_35e3c5b1_like ON public.result_x_laboratories USING btree (x_id varchar_pattern_ops);


--
-- Name: results_result_id_8d59fa3b_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX results_result_id_8d59fa3b_like ON public.results USING btree (result_id varchar_pattern_ops);


--
-- Name: samples_lab_id_id_b8e10de9; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX samples_lab_id_id_b8e10de9 ON public.samples USING btree (lab_id_id);


--
-- Name: samples_lab_id_id_b8e10de9_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX samples_lab_id_id_b8e10de9_like ON public.samples USING btree (lab_id_id varchar_pattern_ops);


--
-- Name: samples_sample_id_da05c421_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX samples_sample_id_da05c421_like ON public.samples USING btree (sample_id varchar_pattern_ops);


--
-- Name: samples_sr_id_id_116929be; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX samples_sr_id_id_116929be ON public.samples USING btree (sr_id_id);


--
-- Name: samples_sr_id_id_116929be_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX samples_sr_id_id_116929be_like ON public.samples USING btree (sr_id_id varchar_pattern_ops);


--
-- Name: service_requests_lab_id_id_4e7a6467; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX service_requests_lab_id_id_4e7a6467 ON public.service_requests USING btree (lab_id_id);


--
-- Name: service_requests_lab_id_id_4e7a6467_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX service_requests_lab_id_id_4e7a6467_like ON public.service_requests USING btree (lab_id_id varchar_pattern_ops);


--
-- Name: service_requests_proposal_id_id_a61f0fa6; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX service_requests_proposal_id_id_a61f0fa6 ON public.service_requests USING btree (proposal_id_id);


--
-- Name: service_requests_proposal_id_id_a61f0fa6_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX service_requests_proposal_id_id_a61f0fa6_like ON public.service_requests USING btree (proposal_id_id varchar_pattern_ops);


--
-- Name: service_requests_sr_id_070fece8_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX service_requests_sr_id_070fece8_like ON public.service_requests USING btree (sr_id varchar_pattern_ops);


--
-- Name: steps_instrument_id_id_e9ada339; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX steps_instrument_id_id_e9ada339 ON public.steps USING btree (instrument_id_id);


--
-- Name: steps_instrument_id_id_e9ada339_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX steps_instrument_id_id_e9ada339_like ON public.steps USING btree (instrument_id_id varchar_pattern_ops);


--
-- Name: steps_sample_id_id_f11ebfd8; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX steps_sample_id_id_f11ebfd8 ON public.steps USING btree (sample_id_id);


--
-- Name: steps_sample_id_id_f11ebfd8_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX steps_sample_id_id_f11ebfd8_like ON public.steps USING btree (sample_id_id varchar_pattern_ops);


--
-- Name: steps_step_id_2299c1e5_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX steps_step_id_2299c1e5_like ON public.steps USING btree (step_id varchar_pattern_ops);


--
-- Name: steps_technique_id_id_79755905; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX steps_technique_id_id_79755905 ON public.steps USING btree (technique_id_id);


--
-- Name: steps_technique_id_id_79755905_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX steps_technique_id_id_79755905_like ON public.steps USING btree (technique_id_id varchar_pattern_ops);


--
-- Name: techniques_technique_id_56008478_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX techniques_technique_id_56008478_like ON public.techniques USING btree (technique_id varchar_pattern_ops);


--
-- Name: users_user_id_26693996_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX users_user_id_26693996_like ON public.users USING btree (user_id varchar_pattern_ops);


--
-- Name: bio_open_lab_unisalentometadata bio_open_lab_unisale_sample_id_6363fc37_fk_samples_s; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.bio_open_lab_unisalentometadata
    ADD CONSTRAINT bio_open_lab_unisale_sample_id_6363fc37_fk_samples_s FOREIGN KEY (sample_id) REFERENCES public.samples(sample_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: bioopenlabunisalento_samples bioopenlabunisalento_samples_ptr_id_44136c80_fk_samples_s; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.bioopenlabunisalento_samples
    ADD CONSTRAINT bioopenlabunisalento_samples_ptr_id_44136c80_fk_samples_s FOREIGN KEY (samples_ptr_id) REFERENCES public.samples(sample_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: experiment_dmp_x_instrument experiment_dmp_x_ins_experiment_dmp_id_82c1580a_fk_experimen; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.experiment_dmp_x_instrument
    ADD CONSTRAINT experiment_dmp_x_ins_experiment_dmp_id_82c1580a_fk_experimen FOREIGN KEY (experiment_dmp_id) REFERENCES public.experiment_dmp(experiment_dmp_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: experiment_dmp_x_instrument experiment_dmp_x_ins_instruments_id_96518eb5_fk_instrumen; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.experiment_dmp_x_instrument
    ADD CONSTRAINT experiment_dmp_x_ins_instruments_id_96518eb5_fk_instrumen FOREIGN KEY (instruments_id) REFERENCES public.instruments(instrument_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: experiment_dmp_x_lab experiment_dmp_x_lab_experiment_dmp_id_24bbc56b_fk_experimen; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.experiment_dmp_x_lab
    ADD CONSTRAINT experiment_dmp_x_lab_experiment_dmp_id_24bbc56b_fk_experimen FOREIGN KEY (experiment_dmp_id) REFERENCES public.experiment_dmp(experiment_dmp_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: experiment_dmp_x_lab experiment_dmp_x_lab_lab_id_eadcf955_fk_laboratories_lab_id; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.experiment_dmp_x_lab
    ADD CONSTRAINT experiment_dmp_x_lab_lab_id_eadcf955_fk_laboratories_lab_id FOREIGN KEY (lab_id) REFERENCES public.laboratories(lab_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: experiment_dmp_x_sample experiment_dmp_x_sam_experiment_dmp_id_7db23d1b_fk_experimen; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.experiment_dmp_x_sample
    ADD CONSTRAINT experiment_dmp_x_sam_experiment_dmp_id_7db23d1b_fk_experimen FOREIGN KEY (experiment_dmp_id) REFERENCES public.experiment_dmp(experiment_dmp_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: experiment_dmp_x_sample experiment_dmp_x_sam_samples_id_636b93ea_fk_samples_s; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.experiment_dmp_x_sample
    ADD CONSTRAINT experiment_dmp_x_sam_samples_id_636b93ea_fk_samples_s FOREIGN KEY (samples_id) REFERENCES public.samples(sample_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: instrument_x_technique instrument_x_techniq_instrument_id_id_2775fa5a_fk_instrumen; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.instrument_x_technique
    ADD CONSTRAINT instrument_x_techniq_instrument_id_id_2775fa5a_fk_instrumen FOREIGN KEY (instrument_id_id) REFERENCES public.instruments(instrument_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: instrument_x_technique instrument_x_techniq_technique_id_id_67a1725a_fk_technique; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.instrument_x_technique
    ADD CONSTRAINT instrument_x_techniq_technique_id_id_67a1725a_fk_technique FOREIGN KEY (technique_id_id) REFERENCES public.techniques(technique_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: lab_x_instrument lab_x_instrument_instrument_id_id_61b2ee3a_fk_instrumen; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.lab_x_instrument
    ADD CONSTRAINT lab_x_instrument_instrument_id_id_61b2ee3a_fk_instrumen FOREIGN KEY (instrument_id_id) REFERENCES public.instruments(instrument_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: lab_x_instrument lab_x_instrument_lab_id_id_cf79aee8_fk_laboratories_lab_id; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.lab_x_instrument
    ADD CONSTRAINT lab_x_instrument_lab_id_id_cf79aee8_fk_laboratories_lab_id FOREIGN KEY (lab_id_id) REFERENCES public.laboratories(lab_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: lage_samples lage_samples_samples_ptr_id_ee82f820_fk_samples_sample_id; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.lage_samples
    ADD CONSTRAINT lage_samples_samples_ptr_id_ee82f820_fk_samples_sample_id FOREIGN KEY (samples_ptr_id) REFERENCES public.samples(sample_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: lame_samples lame_samples_samples_ptr_id_d6261525_fk_samples_sample_id; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.lame_samples
    ADD CONSTRAINT lame_samples_samples_ptr_id_d6261525_fk_samples_sample_id FOREIGN KEY (samples_ptr_id) REFERENCES public.samples(sample_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: proposals proposals_user_id_id_10217a25_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.proposals
    ADD CONSTRAINT proposals_user_id_id_10217a25_fk_users_user_id FOREIGN KEY (user_id_id) REFERENCES public.users(user_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: questions questions_sample_id_id_f5a232cc_fk_samples_sample_id; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT questions_sample_id_id_f5a232cc_fk_samples_sample_id FOREIGN KEY (sample_id_id) REFERENCES public.samples(sample_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: result_x_experiment_dmp result_x_experiment__experiment_dmp_id_14ff90d9_fk_experimen; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.result_x_experiment_dmp
    ADD CONSTRAINT result_x_experiment__experiment_dmp_id_14ff90d9_fk_experimen FOREIGN KEY (experiment_dmp_id) REFERENCES public.experiment_dmp(experiment_dmp_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: result_x_experiment_dmp result_x_experiment_dmp_result_id_3f62147c_fk_results_result_id; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.result_x_experiment_dmp
    ADD CONSTRAINT result_x_experiment_dmp_result_id_3f62147c_fk_results_result_id FOREIGN KEY (result_id) REFERENCES public.results(result_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: result_x_laboratories result_x_laboratories_lab_id_c0c876a7_fk_laboratories_lab_id; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.result_x_laboratories
    ADD CONSTRAINT result_x_laboratories_lab_id_c0c876a7_fk_laboratories_lab_id FOREIGN KEY (lab_id) REFERENCES public.laboratories(lab_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: result_x_laboratories result_x_laboratories_result_id_69dd30a6_fk_results_result_id; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.result_x_laboratories
    ADD CONSTRAINT result_x_laboratories_result_id_69dd30a6_fk_results_result_id FOREIGN KEY (result_id) REFERENCES public.results(result_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: samples samples_lab_id_id_b8e10de9_fk_laboratories_lab_id; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.samples
    ADD CONSTRAINT samples_lab_id_id_b8e10de9_fk_laboratories_lab_id FOREIGN KEY (lab_id_id) REFERENCES public.laboratories(lab_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: samples samples_sr_id_id_116929be_fk_service_requests_sr_id; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.samples
    ADD CONSTRAINT samples_sr_id_id_116929be_fk_service_requests_sr_id FOREIGN KEY (sr_id_id) REFERENCES public.service_requests(sr_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: service_requests service_requests_lab_id_id_4e7a6467_fk_laboratories_lab_id; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.service_requests
    ADD CONSTRAINT service_requests_lab_id_id_4e7a6467_fk_laboratories_lab_id FOREIGN KEY (lab_id_id) REFERENCES public.laboratories(lab_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: service_requests service_requests_proposal_id_id_a61f0fa6_fk_proposals; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.service_requests
    ADD CONSTRAINT service_requests_proposal_id_id_a61f0fa6_fk_proposals FOREIGN KEY (proposal_id_id) REFERENCES public.proposals(proposal_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: steps steps_instrument_id_id_e9ada339_fk_instruments_instrument_id; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.steps
    ADD CONSTRAINT steps_instrument_id_id_e9ada339_fk_instruments_instrument_id FOREIGN KEY (instrument_id_id) REFERENCES public.instruments(instrument_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: steps steps_sample_id_id_f11ebfd8_fk_samples_sample_id; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.steps
    ADD CONSTRAINT steps_sample_id_id_f11ebfd8_fk_samples_sample_id FOREIGN KEY (sample_id_id) REFERENCES public.samples(sample_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: steps steps_technique_id_id_79755905_fk_techniques_technique_id; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.steps
    ADD CONSTRAINT steps_technique_id_id_79755905_fk_techniques_technique_id FOREIGN KEY (technique_id_id) REFERENCES public.techniques(technique_id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

