# Generated by Django 5.1.6 on 2025-02-26 14:46

from django.db import migrations, models

class Migration(migrations.Migration):

    def add_laboratory_field(apps, schema_editor):
        Group = apps.get_model('auth', 'Group')
        schema_editor.execute("ALTER TABLE auth_group ADD COLUMN laboratory BOOLEAN DEFAULT FALSE;")

    dependencies = [
        ('home', '0002_api_tokens_apisettings_dmppage_dmpsearchpage_and_more'),
    ]

    operations = [
        migrations.RunPython(add_laboratory_field),
    ]
