# Generated by Django 5.1.6 on 2025-02-11 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_apisettings_dmppage_dmpsearchpage_dmpviewpage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='API_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laboratory', models.CharField(max_length=50)),
                ('elab_token', models.CharField(blank=True, max_length=128, null=True)),
                ('jenkins_token', models.CharField(blank=True, max_length=128, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_tokens',
            },
        ),
    ]
