# Generated by Django 5.1.6 on 2025-02-14 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_dmpviewpage_intro_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDataPage',
        ),
    ]
