# Generated by Django 5.1.6 on 2025-02-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_switchlabpage'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExperimentDMPPage',
            new_name='ExperimentMetadataReportPage',
        ),
        migrations.AlterField(
            model_name='dmppage',
            name='thankyou_page_title',
            field=models.CharField(help_text='Title text displayed after DMP submission', max_length=255),
        ),
    ]
