--
-- PostgreSQL database dump
--

-- Dumped from database version 16.8 (Debian 16.8-1.pgdg120+1)
-- Dumped by pg_dump version 16.8 (Debian 16.8-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: PRP_CDM_app_experimentdatamanagementplan; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public."PRP_CDM_app_experimentdatamanagementplan" (
    experiment_dmp_id character varying(50) NOT NULL
);


ALTER TABLE public."PRP_CDM_app_experimentdatamanagementplan" OWNER TO decos;

--
-- Name: administration; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.administration (
    sr_id character varying(50) NOT NULL,
    lab_id character varying(50) NOT NULL,
    dmptitle character varying(128) NOT NULL,
    user_id character varying(50) NOT NULL,
    email character varying(128) NOT NULL,
    affiliation character varying(128) NOT NULL,
    experimentabstract text NOT NULL
);


ALTER TABLE public.administration OWNER TO decos;

--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO decos;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: decos
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: experimentdmp_x_filesinfo; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.experimentdmp_x_filesinfo (
    x_id character varying(50) NOT NULL,
    experimentdmp_id character varying(50) NOT NULL,
    file_info_id character varying(50) NOT NULL
);


ALTER TABLE public.experimentdmp_x_filesinfo OWNER TO decos;

--
-- Name: experimentdmp_x_instrument; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.experimentdmp_x_instrument (
    x_id character varying(50) NOT NULL,
    experimentdmp_id character varying(50) NOT NULL,
    instruments_id character varying(50) NOT NULL
);


ALTER TABLE public.experimentdmp_x_instrument OWNER TO decos;

--
-- Name: experimentdmp_x_lab; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.experimentdmp_x_lab (
    x_id character varying(50) NOT NULL,
    experimentdmp_id character varying(50) NOT NULL,
    lab_id character varying(50) NOT NULL
);


ALTER TABLE public.experimentdmp_x_lab OWNER TO decos;

--
-- Name: experimentdmp_x_sample; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.experimentdmp_x_sample (
    x_id character varying(50) NOT NULL,
    experimentdmp_id character varying(50) NOT NULL,
    samples_id character varying(50) NOT NULL
);


ALTER TABLE public.experimentdmp_x_sample OWNER TO decos;

--
-- Name: fileinfo_x_lab; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.fileinfo_x_lab (
    x_id character varying(50) NOT NULL,
    file_info_id character varying(50) NOT NULL,
    lab_id character varying(50) NOT NULL
);


ALTER TABLE public.fileinfo_x_lab OWNER TO decos;

--
-- Name: filesinfo; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.filesinfo (
    file_info_id character varying(50) NOT NULL,
    extension character varying(128) NOT NULL,
    is_open boolean NOT NULL,
    software_used character varying(128) NOT NULL
);


ALTER TABLE public.filesinfo OWNER TO decos;

--
-- Name: instrument_x_technique; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.instrument_x_technique (
    x_id character varying(50) NOT NULL,
    instrument_id_id character varying(50) NOT NULL,
    technique_id_id character varying(50) NOT NULL
);


ALTER TABLE public.instrument_x_technique OWNER TO decos;

--
-- Name: instruments; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.instruments (
    instrument_id character varying(50) NOT NULL,
    vendor character varying(50) NOT NULL,
    model character varying(50) NOT NULL,
    description character varying(50) NOT NULL
);


ALTER TABLE public.instruments OWNER TO decos;

--
-- Name: lab_x_instrument; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.lab_x_instrument (
    id bigint NOT NULL,
    instrument_id_id character varying(50) NOT NULL,
    lab_id_id character varying(50) NOT NULL
);


ALTER TABLE public.lab_x_instrument OWNER TO decos;

--
-- Name: lab_x_instrument_id_seq; Type: SEQUENCE; Schema: public; Owner: decos
--

ALTER TABLE public.lab_x_instrument ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lab_x_instrument_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: labdmp; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.labdmp (
    lab_id character varying(128) NOT NULL,
    user_id character varying(50) NOT NULL,
    instrument_metadata_collection character varying(128) NOT NULL,
    additional_enotebook_open_collection character varying(128) NOT NULL,
    sample_standard character varying(128) NOT NULL,
    metadata_schema_defined character varying NOT NULL,
    open_trusted_repo_published_data boolean NOT NULL,
    open_data_licence character varying NOT NULL,
    open_access_journal_publication boolean NOT NULL,
    clear_data_provenance boolean NOT NULL,
    related_data_open boolean NOT NULL,
    licence_scientific_documents boolean NOT NULL,
    raw_data_storage_location character varying NOT NULL,
    raw_data_storage_time_retention character varying NOT NULL,
    backup_policy_published_data character varying NOT NULL,
    backup_policy_unplublished_data character varying NOT NULL
);


ALTER TABLE public.labdmp OWNER TO decos;

--
-- Name: laboratories; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.laboratories (
    lab_id character varying(50) NOT NULL,
    description character varying(50) NOT NULL
);


ALTER TABLE public.laboratories OWNER TO decos;

--
-- Name: lage_samples; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.lage_samples (
    samples_ptr_id character varying(50) NOT NULL,
    type character varying NOT NULL,
    is_volume_in_ul character varying NOT NULL,
    is_buffer_used character varying NOT NULL,
    is_quality character varying NOT NULL,
    sample_date_of_delivery date NOT NULL,
    sample_back boolean NOT NULL,
    reagents_provided_by_client boolean NOT NULL,
    reagents_date_of_delivery date,
    sample_sheet_filename character varying(100) NOT NULL,
    additional_filename character varying(100) NOT NULL
);


ALTER TABLE public.lage_samples OWNER TO decos;

--
-- Name: lame_samples; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.lame_samples (
    samples_ptr_id character varying(50) NOT NULL,
    chemical_formula character varying NOT NULL,
    elements_list character varying NOT NULL,
    sample_date_of_delivery date NOT NULL,
    sample_back boolean NOT NULL,
    sample_sheet_filename character varying(100) NOT NULL,
    additional_filename character varying(100) NOT NULL
);


ALTER TABLE public.lame_samples OWNER TO decos;

--
-- Name: proposals; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.proposals (
    proposal_id character varying(50) NOT NULL,
    proposal_status character varying NOT NULL,
    proposal_feasibility character varying NOT NULL,
    proposal_date date NOT NULL,
    proposal_filename character varying(100) NOT NULL,
    user_id_id character varying(50) NOT NULL
);


ALTER TABLE public.proposals OWNER TO decos;

--
-- Name: questions; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.questions (
    question_id character varying(50) NOT NULL,
    question text NOT NULL,
    answer text NOT NULL,
    sample_id_id character varying(50) NOT NULL
);


ALTER TABLE public.questions OWNER TO decos;

--
-- Name: result_x_instrument; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.result_x_instrument (
    x_id character varying(50) NOT NULL,
    instruments_id character varying(50) NOT NULL,
    results_id character varying(50) NOT NULL
);


ALTER TABLE public.result_x_instrument OWNER TO decos;

--
-- Name: result_x_lab; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.result_x_lab (
    x_id character varying(50) NOT NULL,
    lab_id character varying(50) NOT NULL,
    results_id character varying(50) NOT NULL
);


ALTER TABLE public.result_x_lab OWNER TO decos;

--
-- Name: result_x_sample; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.result_x_sample (
    x_id character varying(50) NOT NULL,
    results_id character varying(50) NOT NULL,
    samples_id character varying(50) NOT NULL
);


ALTER TABLE public.result_x_sample OWNER TO decos;

--
-- Name: results; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.results (
    result_id character varying(50) NOT NULL,
    main_repository character varying(2048) NOT NULL,
    article_doi character varying(256) NOT NULL
);


ALTER TABLE public.results OWNER TO decos;

--
-- Name: samples; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.samples (
    sample_id character varying(50) NOT NULL,
    sample_short_description character varying(64) NOT NULL,
    sample_description text NOT NULL,
    sample_feasibility character varying NOT NULL,
    sample_status character varying NOT NULL,
    sample_location character varying,
    lab_id_id character varying(50) NOT NULL,
    sr_id_id character varying(50)
);


ALTER TABLE public.samples OWNER TO decos;

--
-- Name: service_requests; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.service_requests (
    sr_id character varying(50) NOT NULL,
    sr_status character varying NOT NULL,
    exp_description text NOT NULL,
    output_delivery_date date NOT NULL,
    lab_id_id character varying(50) NOT NULL,
    proposal_id_id character varying(50) NOT NULL
);


ALTER TABLE public.service_requests OWNER TO decos;

--
-- Name: steps; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.steps (
    step_id character varying(50) NOT NULL,
    assigned_uoa integer NOT NULL,
    performed_uoa integer NOT NULL,
    eff_sample_date_of_delivery date NOT NULL,
    eff_reagents_date_of_delivery date NOT NULL,
    sample_quality character varying NOT NULL,
    sample_quality_description text NOT NULL,
    sample_quality_extra_budjet boolean NOT NULL,
    instrument_id_id character varying(50) NOT NULL,
    sample_id_id character varying(50) NOT NULL,
    technique_id_id character varying(50) NOT NULL
);


ALTER TABLE public.steps OWNER TO decos;

--
-- Name: techniques; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.techniques (
    technique_id character varying(50) NOT NULL,
    technique_name character varying(50) NOT NULL,
    description character varying(50) NOT NULL
);


ALTER TABLE public.techniques OWNER TO decos;

--
-- Name: users; Type: TABLE; Schema: public; Owner: decos
--

CREATE TABLE public.users (
    user_id character varying(50) NOT NULL,
    name_surname character varying(50) NOT NULL,
    email character varying(128) NOT NULL,
    affiliation character varying(128) NOT NULL,
    gender character varying NOT NULL,
    legal_status character varying,
    research_role character varying NOT NULL
);


ALTER TABLE public.users OWNER TO decos;

--
-- Data for Name: PRP_CDM_app_experimentdatamanagementplan; Type: TABLE DATA; Schema: public; Owner: decos
--

COPY public."PRP_CDM_app_experimentdatamanagementplan" (experiment_dmp_id) FROM stdin;
\.


--
-- Data for Name: administration; Type: TABLE DATA; Schema: public; Owner: decos
--

COPY public.administration (sr_id, lab_id, dmptitle, user_id, email, affiliation, experimentabstract) FROM stdin;
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: decos
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	PRP_CDM_app	0001_initial	2025-02-27 17:09:17.615387+00
2	contenttypes	0001_initial	2025-02-27 17:09:17.61825+00
3	auth	0001_initial	2025-02-27 17:09:17.623271+00
4	account	0001_initial	2025-02-27 17:09:17.631455+00
5	account	0002_email_max_length	2025-02-27 17:09:17.635155+00
6	account	0003_alter_emailaddress_create_unique_verified_email	2025-02-27 17:09:17.643122+00
7	account	0004_alter_emailaddress_drop_unique_email	2025-02-27 17:09:17.646641+00
8	account	0005_emailaddress_idx_upper_email	2025-02-27 17:09:17.649517+00
9	account	0006_emailaddress_lower	2025-02-27 17:09:17.650183+00
10	account	0007_emailaddress_idx_email	2025-02-27 17:09:17.656371+00
11	account	0008_emailaddress_unique_primary_email_fixup	2025-02-27 17:09:17.658185+00
12	account	0009_emailaddress_unique_primary_email	2025-02-27 17:09:17.662111+00
13	admin	0001_initial	2025-02-27 17:09:17.665832+00
14	admin	0002_logentry_remove_auto_add	2025-02-27 17:09:17.670148+00
15	admin	0003_logentry_add_action_flag_choices	2025-02-27 17:09:17.677851+00
16	contenttypes	0002_remove_content_type_name	2025-02-27 17:09:17.681841+00
17	auth	0002_alter_permission_name_max_length	2025-02-27 17:09:17.686634+00
18	auth	0003_alter_user_email_max_length	2025-02-27 17:09:17.689653+00
19	auth	0004_alter_user_username_opts	2025-02-27 17:09:17.693552+00
20	auth	0005_alter_user_last_login_null	2025-02-27 17:09:17.6997+00
21	auth	0006_require_contenttypes_0002	2025-02-27 17:09:17.700143+00
22	auth	0007_alter_validators_add_error_messages	2025-02-27 17:09:17.70334+00
23	auth	0008_alter_user_username_max_length	2025-02-27 17:09:17.707622+00
24	auth	0009_alter_user_last_name_max_length	2025-02-27 17:09:17.710363+00
25	auth	0010_alter_group_name_max_length	2025-02-27 17:09:17.715878+00
26	auth	0011_update_proxy_permissions	2025-02-27 17:09:17.717206+00
27	auth	0012_alter_user_first_name_max_length	2025-02-27 17:09:17.721431+00
28	wagtailcore	0001_initial	2025-02-27 17:09:17.819379+00
29	wagtailcore	0002_initial_data	2025-02-27 17:09:17.820165+00
30	wagtailcore	0003_add_uniqueness_constraint_on_group_page_permission	2025-02-27 17:09:17.820409+00
31	wagtailcore	0004_page_locked	2025-02-27 17:09:17.820622+00
32	wagtailcore	0005_add_page_lock_permission_to_moderators	2025-02-27 17:09:17.820818+00
33	wagtailcore	0006_add_lock_page_permission	2025-02-27 17:09:17.821003+00
34	wagtailcore	0007_page_latest_revision_created_at	2025-02-27 17:09:17.82121+00
35	wagtailcore	0008_populate_latest_revision_created_at	2025-02-27 17:09:17.821415+00
36	wagtailcore	0009_remove_auto_now_add_from_pagerevision_created_at	2025-02-27 17:09:17.821592+00
37	wagtailcore	0010_change_page_owner_to_null_on_delete	2025-02-27 17:09:17.821776+00
38	wagtailcore	0011_page_first_published_at	2025-02-27 17:09:17.821964+00
39	wagtailcore	0012_extend_page_slug_field	2025-02-27 17:09:17.822121+00
40	wagtailcore	0013_update_golive_expire_help_text	2025-02-27 17:09:17.822267+00
41	wagtailcore	0014_add_verbose_name	2025-02-27 17:09:17.822418+00
42	wagtailcore	0015_add_more_verbose_names	2025-02-27 17:09:17.822583+00
43	wagtailcore	0016_change_page_url_path_to_text_field	2025-02-27 17:09:17.822718+00
44	wagtailcore	0017_change_edit_page_permission_description	2025-02-27 17:09:17.827733+00
45	wagtailcore	0018_pagerevision_submitted_for_moderation_index	2025-02-27 17:09:17.832873+00
46	wagtailcore	0019_verbose_names_cleanup	2025-02-27 17:09:17.851611+00
47	wagtailcore	0020_add_index_on_page_first_published_at	2025-02-27 17:09:17.856629+00
48	wagtailcore	0021_capitalizeverbose	2025-02-27 17:09:18.01308+00
49	wagtailcore	0022_add_site_name	2025-02-27 17:09:18.018693+00
50	wagtailcore	0023_alter_page_revision_on_delete_behaviour	2025-02-27 17:09:18.02346+00
51	wagtailcore	0024_collection	2025-02-27 17:09:18.02441+00
52	wagtailcore	0025_collection_initial_data	2025-02-27 17:09:18.024938+00
53	wagtailcore	0026_group_collection_permission	2025-02-27 17:09:18.033916+00
54	wagtailcore	0027_fix_collection_path_collation	2025-02-27 17:09:18.034789+00
55	wagtailcore	0024_alter_page_content_type_on_delete_behaviour	2025-02-27 17:09:18.040121+00
56	wagtailcore	0028_merge	2025-02-27 17:09:18.040609+00
57	wagtailcore	0029_unicode_slugfield_dj19	2025-02-27 17:09:18.046367+00
58	wagtailcore	0030_index_on_pagerevision_created_at	2025-02-27 17:09:18.050572+00
59	wagtailcore	0031_add_page_view_restriction_types	2025-02-27 17:09:18.068263+00
60	wagtailcore	0032_add_bulk_delete_page_permission	2025-02-27 17:09:18.074173+00
61	wagtailcore	0033_remove_golive_expiry_help_text	2025-02-27 17:09:18.083336+00
62	wagtailcore	0034_page_live_revision	2025-02-27 17:09:18.089476+00
63	wagtailcore	0035_page_last_published_at	2025-02-27 17:09:18.097598+00
64	wagtailcore	0036_populate_page_last_published_at	2025-02-27 17:09:18.098313+00
65	wagtailcore	0037_set_page_owner_editable	2025-02-27 17:09:18.104663+00
66	wagtailcore	0038_make_first_published_at_editable	2025-02-27 17:09:18.111938+00
67	wagtailcore	0039_collectionviewrestriction	2025-02-27 17:09:18.138415+00
68	wagtailcore	0040_page_draft_title	2025-02-27 17:09:18.225054+00
69	wagtailcore	0041_group_collection_permissions_verbose_name_plural	2025-02-27 17:09:18.234845+00
70	wagtailcore	0042_index_on_pagerevision_approved_go_live_at	2025-02-27 17:09:18.24566+00
71	wagtailcore	0043_lock_fields	2025-02-27 17:09:18.272469+00
72	wagtailcore	0044_add_unlock_grouppagepermission	2025-02-27 17:09:18.28498+00
73	wagtailcore	0045_assign_unlock_grouppagepermission	2025-02-27 17:09:18.287994+00
74	wagtailcore	0046_site_name_remove_null	2025-02-27 17:09:18.297574+00
75	wagtailcore	0047_add_workflow_models	2025-02-27 17:09:18.476429+00
76	wagtailcore	0048_add_default_workflows	2025-02-27 17:09:18.47964+00
77	wagtailcore	0049_taskstate_finished_by	2025-02-27 17:09:18.496899+00
78	wagtailcore	0050_workflow_rejected_to_needs_changes	2025-02-27 17:09:18.52226+00
79	wagtailcore	0051_taskstate_comment	2025-02-27 17:09:18.530466+00
80	wagtailcore	0052_pagelogentry	2025-02-27 17:09:18.545198+00
81	wagtailcore	0053_locale_model	2025-02-27 17:09:18.547151+00
82	wagtailcore	0054_initial_locale	2025-02-27 17:09:18.547979+00
83	wagtailcore	0055_page_locale_fields	2025-02-27 17:09:18.580096+00
84	wagtailcore	0056_page_locale_fields_populate	2025-02-27 17:09:18.587604+00
85	wagtailcore	0057_page_locale_fields_notnull	2025-02-27 17:09:18.617145+00
86	wagtailcore	0058_page_alias_of	2025-02-27 17:09:18.634949+00
87	wagtailcore	0059_apply_collection_ordering	2025-02-27 17:09:18.638203+00
88	wagtailcore	0060_fix_workflow_unique_constraint	2025-02-27 17:09:18.677678+00
89	wagtailcore	0061_change_promote_tab_helpt_text_and_verbose_names	2025-02-27 17:09:18.699964+00
90	wagtailcore	0062_comment_models_and_pagesubscription	2025-02-27 17:09:18.831322+00
91	wagtailcore	0063_modellogentry	2025-02-27 17:09:18.840858+00
92	wagtailcore	0064_log_timestamp_indexes	2025-02-27 17:09:18.854152+00
93	wagtailcore	0065_log_entry_uuid	2025-02-27 17:09:18.867581+00
94	wagtailcore	0066_collection_management_permissions	2025-02-27 17:09:18.868539+00
95	wagtailcore	0067_alter_pagerevision_content_json	2025-02-27 17:09:18.884668+00
96	wagtailcore	0068_log_entry_empty_object	2025-02-27 17:09:18.885607+00
97	wagtailcore	0069_log_entry_jsonfield	2025-02-27 17:09:18.911491+00
98	wagtailcore	0070_rename_pagerevision_revision	2025-02-27 17:09:18.979624+00
99	wagtailcore	0071_populate_revision_content_type	2025-02-27 17:09:18.980976+00
100	wagtailcore	0072_alter_revision_content_type_notnull	2025-02-27 17:09:19.009716+00
101	wagtailcore	0073_page_latest_revision	2025-02-27 17:09:19.026251+00
102	wagtailcore	0074_revision_object_str	2025-02-27 17:09:19.041474+00
103	wagtailcore	0075_populate_latest_revision_and_revision_object_str	2025-02-27 17:09:19.043476+00
104	wagtailcore	0076_modellogentry_revision	2025-02-27 17:09:19.05348+00
105	wagtailcore	0077_alter_revision_user	2025-02-27 17:09:19.106956+00
106	wagtailcore	0078_referenceindex	2025-02-27 17:09:19.1167+00
107	wagtailcore	0079_rename_taskstate_page_revision	2025-02-27 17:09:19.124463+00
108	wagtailcore	0080_generic_workflowstate	2025-02-27 17:09:19.185799+00
109	wagtailcore	0081_populate_workflowstate_content_type	2025-02-27 17:09:19.186946+00
110	wagtailcore	0082_alter_workflowstate_content_type_notnull	2025-02-27 17:09:19.206061+00
111	wagtailcore	0083_workflowcontenttype	2025-02-27 17:09:19.216437+00
112	wagtailcore	0084_add_default_page_permissions	2025-02-27 17:09:19.225349+00
113	wagtailcore	0085_add_grouppagepermission_permission	2025-02-27 17:09:19.246874+00
114	wagtailcore	0086_populate_grouppagepermission_permission	2025-02-27 17:09:19.248445+00
115	wagtailcore	0087_alter_grouppagepermission_unique_together_and_more	2025-02-27 17:09:19.273021+00
116	wagtailcore	0088_fix_log_entry_json_timestamps	2025-02-27 17:09:19.2876+00
117	wagtailcore	0089_log_entry_data_json_null_to_object	2025-02-27 17:09:19.288425+00
118	wagtailcore	0090_remove_grouppagepermission_permission_type	2025-02-27 17:09:19.365563+00
119	wagtailcore	0091_remove_revision_submitted_for_moderation	2025-02-27 17:09:19.372795+00
120	wagtailcore	0092_alter_collectionviewrestriction_password_and_more	2025-02-27 17:09:19.396236+00
121	wagtailcore	0093_uploadedfile	2025-02-27 17:09:19.406203+00
122	wagtailcore	0094_alter_page_locale	2025-02-27 17:09:19.416631+00
123	taggit	0001_initial	2025-02-27 17:09:19.426612+00
124	wagtailimages	0001_initial	2025-02-27 17:09:19.453964+00
125	wagtailimages	0002_initial_data	2025-02-27 17:09:19.45444+00
126	wagtailimages	0003_fix_focal_point_fields	2025-02-27 17:09:19.454586+00
127	wagtailimages	0004_make_focal_point_key_not_nullable	2025-02-27 17:09:19.454697+00
128	wagtailimages	0005_make_filter_spec_unique	2025-02-27 17:09:19.454799+00
129	wagtailimages	0006_add_verbose_names	2025-02-27 17:09:19.454894+00
130	wagtailimages	0007_image_file_size	2025-02-27 17:09:19.454991+00
131	wagtailimages	0008_image_created_at_index	2025-02-27 17:09:19.455084+00
132	wagtailimages	0009_capitalizeverbose	2025-02-27 17:09:19.455181+00
133	wagtailimages	0010_change_on_delete_behaviour	2025-02-27 17:09:19.455273+00
134	wagtailimages	0011_image_collection	2025-02-27 17:09:19.455364+00
135	wagtailimages	0012_copy_image_permissions_to_collections	2025-02-27 17:09:19.455453+00
136	wagtailimages	0013_make_rendition_upload_callable	2025-02-27 17:09:19.455551+00
137	wagtailimages	0014_add_filter_spec_field	2025-02-27 17:09:19.455638+00
138	wagtailimages	0015_fill_filter_spec_field	2025-02-27 17:09:19.455745+00
139	wagtailimages	0016_deprecate_rendition_filter_relation	2025-02-27 17:09:19.455837+00
140	wagtailimages	0017_reduce_focal_point_key_max_length	2025-02-27 17:09:19.455928+00
141	wagtailimages	0018_remove_rendition_filter	2025-02-27 17:09:19.456014+00
142	wagtailimages	0019_delete_filter	2025-02-27 17:09:19.456101+00
143	wagtailimages	0020_add-verbose-name	2025-02-27 17:09:19.456188+00
144	wagtailimages	0021_image_file_hash	2025-02-27 17:09:19.456286+00
145	wagtailimages	0022_uploadedimage	2025-02-27 17:09:19.467152+00
146	wagtailadmin	0001_create_admin_access_permissions	2025-02-27 17:09:19.468005+00
147	wagtailimages	0023_add_choose_permissions	2025-02-27 17:09:19.47815+00
148	wagtailimages	0024_index_image_file_hash	2025-02-27 17:09:19.487453+00
149	wagtailimages	0025_alter_image_file_alter_rendition_file	2025-02-27 17:09:19.500462+00
150	wagtailimages	0026_delete_uploadedimage	2025-02-27 17:09:19.501429+00
151	wagtailimages	0027_image_description	2025-02-27 17:09:19.509213+00
152	home	0001_initial	2025-02-27 17:09:19.523146+00
153	home	0002_api_tokens_apisettings_dmppage_dmpsearchpage_and_more	2025-02-27 17:09:19.846955+00
154	home	0003_newtestpage	2025-02-27 17:09:19.863957+00
155	sessions	0001_initial	2025-02-27 17:09:19.865084+00
156	socialaccount	0001_initial	2025-02-27 17:09:19.955641+00
157	socialaccount	0002_token_max_lengths	2025-02-27 17:09:19.97203+00
158	socialaccount	0003_extra_data_default_dict	2025-02-27 17:09:19.980997+00
159	socialaccount	0004_app_provider_id_settings	2025-02-27 17:09:19.992932+00
160	socialaccount	0005_socialtoken_nullable_app	2025-02-27 17:09:20.0154+00
161	socialaccount	0006_alter_socialaccount_extra_data	2025-02-27 17:09:20.032889+00
162	taggit	0002_auto_20150616_2121	2025-02-27 17:09:20.039886+00
163	taggit	0003_taggeditem_add_unique_index	2025-02-27 17:09:20.046268+00
164	taggit	0004_alter_taggeditem_content_type_alter_taggeditem_tag	2025-02-27 17:09:20.086839+00
165	taggit	0005_auto_20220424_2025	2025-02-27 17:09:20.104671+00
166	taggit	0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx	2025-02-27 17:09:20.118794+00
167	wagtailadmin	0002_admin	2025-02-27 17:09:20.119923+00
168	wagtailadmin	0003_admin_managed	2025-02-27 17:09:20.121148+00
169	wagtailadmin	0004_editingsession	2025-02-27 17:09:20.138317+00
170	wagtailadmin	0005_editingsession_is_editing	2025-02-27 17:09:20.147653+00
171	wagtaildocs	0001_initial	2025-02-27 17:09:20.167442+00
172	wagtaildocs	0002_initial_data	2025-02-27 17:09:20.168453+00
173	wagtaildocs	0003_add_verbose_names	2025-02-27 17:09:20.213989+00
174	wagtaildocs	0004_capitalizeverbose	2025-02-27 17:09:20.32169+00
175	wagtaildocs	0005_document_collection	2025-02-27 17:09:20.338611+00
176	wagtaildocs	0006_copy_document_permissions_to_collections	2025-02-27 17:09:20.339595+00
177	wagtaildocs	0005_alter_uploaded_by_user_on_delete_action	2025-02-27 17:09:20.356026+00
178	wagtaildocs	0007_merge	2025-02-27 17:09:20.356583+00
179	wagtaildocs	0008_document_file_size	2025-02-27 17:09:20.365997+00
180	wagtaildocs	0009_document_verbose_name_plural	2025-02-27 17:09:20.377482+00
181	wagtaildocs	0010_document_file_hash	2025-02-27 17:09:20.387084+00
182	wagtaildocs	0011_add_choose_permissions	2025-02-27 17:09:20.396386+00
183	wagtaildocs	0012_uploadeddocument	2025-02-27 17:09:20.414534+00
184	wagtaildocs	0013_delete_uploadeddocument	2025-02-27 17:09:20.415656+00
185	wagtaildocs	0014_alter_document_file_size	2025-02-27 17:09:20.434182+00
186	wagtailembeds	0001_initial	2025-02-27 17:09:20.43857+00
187	wagtailembeds	0002_add_verbose_names	2025-02-27 17:09:20.440143+00
188	wagtailembeds	0003_capitalizeverbose	2025-02-27 17:09:20.441648+00
189	wagtailembeds	0004_embed_verbose_name_plural	2025-02-27 17:09:20.442925+00
190	wagtailembeds	0005_specify_thumbnail_url_max_length	2025-02-27 17:09:20.44434+00
191	wagtailembeds	0006_add_embed_hash	2025-02-27 17:09:20.4456+00
192	wagtailembeds	0007_populate_hash	2025-02-27 17:09:20.446205+00
193	wagtailembeds	0008_allow_long_urls	2025-02-27 17:09:20.451285+00
194	wagtailembeds	0009_embed_cache_until	2025-02-27 17:09:20.452528+00
195	wagtailforms	0001_initial	2025-02-27 17:09:20.469209+00
196	wagtailforms	0002_add_verbose_names	2025-02-27 17:09:20.486087+00
197	wagtailforms	0003_capitalizeverbose	2025-02-27 17:09:20.547876+00
198	wagtailforms	0004_add_verbose_name_plural	2025-02-27 17:09:20.556834+00
199	wagtailforms	0005_alter_formsubmission_form_data	2025-02-27 17:09:20.565255+00
200	wagtailredirects	0001_initial	2025-02-27 17:09:20.582196+00
201	wagtailredirects	0002_add_verbose_names	2025-02-27 17:09:20.607713+00
202	wagtailredirects	0003_make_site_field_editable	2025-02-27 17:09:20.62427+00
203	wagtailredirects	0004_set_unique_on_path_and_site	2025-02-27 17:09:20.641273+00
204	wagtailredirects	0005_capitalizeverbose	2025-02-27 17:09:20.726085+00
205	wagtailredirects	0006_redirect_increase_max_length	2025-02-27 17:09:20.739815+00
206	wagtailredirects	0007_add_autocreate_fields	2025-02-27 17:09:20.767843+00
207	wagtailredirects	0008_add_verbose_name_plural	2025-02-27 17:09:20.77788+00
208	wagtailsearch	0001_initial	2025-02-27 17:09:20.887044+00
209	wagtailsearch	0002_add_verbose_names	2025-02-27 17:09:20.948347+00
210	wagtailsearch	0003_remove_editors_pick	2025-02-27 17:09:20.949318+00
211	wagtailsearch	0004_querydailyhits_verbose_name_plural	2025-02-27 17:09:20.951681+00
212	wagtailsearch	0005_create_indexentry	2025-02-27 17:09:20.978841+00
213	wagtailsearch	0006_customise_indexentry	2025-02-27 17:09:21.015154+00
214	wagtailsearch	0007_delete_editorspick	2025-02-27 17:09:21.018975+00
215	wagtailsearch	0008_remove_query_and_querydailyhits_models	2025-02-27 17:09:21.02625+00
216	wagtailusers	0001_initial	2025-02-27 17:09:21.047028+00
217	wagtailusers	0002_add_verbose_name_on_userprofile	2025-02-27 17:09:21.071548+00
218	wagtailusers	0003_add_verbose_names	2025-02-27 17:09:21.079568+00
219	wagtailusers	0004_capitalizeverbose	2025-02-27 17:09:21.111328+00
220	wagtailusers	0005_make_related_name_wagtail_specific	2025-02-27 17:09:21.190158+00
221	wagtailusers	0006_userprofile_prefered_language	2025-02-27 17:09:21.199064+00
222	wagtailusers	0007_userprofile_current_time_zone	2025-02-27 17:09:21.207175+00
223	wagtailusers	0008_userprofile_avatar	2025-02-27 17:09:21.216267+00
224	wagtailusers	0009_userprofile_verbose_name_plural	2025-02-27 17:09:21.22441+00
225	wagtailusers	0010_userprofile_updated_comments_notifications	2025-02-27 17:09:21.23287+00
226	wagtailusers	0011_userprofile_dismissibles	2025-02-27 17:09:21.240861+00
227	wagtailusers	0012_userprofile_theme	2025-02-27 17:09:21.250659+00
228	wagtailusers	0013_userprofile_density	2025-02-27 17:09:21.259992+00
229	wagtailusers	0014_userprofile_contrast	2025-02-27 17:09:21.26851+00
230	wagtailimages	0001_squashed_0021	2025-02-27 17:09:21.270211+00
231	wagtailcore	0001_squashed_0016_change_page_url_path_to_text_field	2025-02-27 17:09:21.270578+00
232	PRP_CDM_app	0002_experimentdatamanagementplan_filesinfo_and_more	2025-03-06 15:07:45.693028+00
233	PRP_CDM_app	0003_fileinfoxlab	2025-03-06 16:08:12.920234+00
234	home	0004_fileinfopage_delete_newtestpage	2025-03-06 16:08:12.953487+00
\.


--
-- Data for Name: experimentdmp_x_filesinfo; Type: TABLE DATA; Schema: public; Owner: decos
--

COPY public.experimentdmp_x_filesinfo (x_id, experimentdmp_id, file_info_id) FROM stdin;
\.


--
-- Data for Name: experimentdmp_x_instrument; Type: TABLE DATA; Schema: public; Owner: decos
--

COPY public.experimentdmp_x_instrument (x_id, experimentdmp_id, instruments_id) FROM stdin;
\.


--
-- Data for Name: experimentdmp_x_lab; Type: TABLE DATA; Schema: public; Owner: decos
--

COPY public.experimentdmp_x_lab (x_id, experimentdmp_id, lab_id) FROM stdin;
\.


--
-- Data for Name: experimentdmp_x_sample; Type: TABLE DATA; Schema: public; Owner: decos
--

COPY public.experimentdmp_x_sample (x_id, experimentdmp_id, samples_id) FROM stdin;
\.


--
-- Data for Name: fileinfo_x_lab; Type: TABLE DATA; Schema: public; Owner: decos
--

COPY public.fileinfo_x_lab (x_id, file_info_id, lab_id) FROM stdin;
	zep_microsoftsoftserver	LAGE
\.


--
-- Data for Name: filesinfo; Type: TABLE DATA; Schema: public; Owner: decos
--

COPY public.filesinfo (file_info_id, extension, is_open, software_used) FROM stdin;
zip_zop	zip	t	zop!
zep_microsoftsoftserver	zep	t	Microsoft Soft Sérver
\.


--
-- Data for Name: instrument_x_technique; Type: TABLE DATA; Schema: public; Owner: decos
--

COPY public.instrument_x_technique (x_id, instrument_id_id, technique_id_id) FROM stdin;
\.


--
-- Data for Name: instruments; Type: TABLE DATA; Schema: public; Owner: decos
--

COPY public.instruments (instrument_id, vendor, model, description) FROM stdin;
\.


--
-- Data for Name: lab_x_instrument; Type: TABLE DATA; Schema: public; Owner: decos
--

COPY public.lab_x_instrument (id, instrument_id_id, lab_id_id) FROM stdin;
\.


--
-- Data for Name: labdmp; Type: TABLE DATA; Schema: public; Owner: decos
--

COPY public.labdmp (lab_id, user_id, instrument_metadata_collection, additional_enotebook_open_collection, sample_standard, metadata_schema_defined, open_trusted_repo_published_data, open_data_licence, open_access_journal_publication, clear_data_provenance, related_data_open, licence_scientific_documents, raw_data_storage_location, raw_data_storage_time_retention, backup_policy_published_data, backup_policy_unplublished_data) FROM stdin;
\.


--
-- Data for Name: laboratories; Type: TABLE DATA; Schema: public; Owner: decos
--

COPY public.laboratories (lab_id, description) FROM stdin;
LAGE	Laboratory of Genetics and Epigenetics
\.


--
-- Data for Name: lage_samples; Type: TABLE DATA; Schema: public; Owner: decos
--

COPY public.lage_samples (samples_ptr_id, type, is_volume_in_ul, is_buffer_used, is_quality, sample_date_of_delivery, sample_back, reagents_provided_by_client, reagents_date_of_delivery, sample_sheet_filename, additional_filename) FROM stdin;
s_internal_00001	DNA	No	No:	No:	2025-01-03	f	f	\N		
s_internal_00002	RNA	No	No: I have a jar	No:	2025-01-03	f	f	\N		
\.


--
-- Data for Name: lame_samples; Type: TABLE DATA; Schema: public; Owner: decos
--

COPY public.lame_samples (samples_ptr_id, chemical_formula, elements_list, sample_date_of_delivery, sample_back, sample_sheet_filename, additional_filename) FROM stdin;
\.


--
-- Data for Name: proposals; Type: TABLE DATA; Schema: public; Owner: decos
--

COPY public.proposals (proposal_id, proposal_status, proposal_feasibility, proposal_date, proposal_filename, user_id_id) FROM stdin;
\.


--
-- Data for Name: questions; Type: TABLE DATA; Schema: public; Owner: decos
--

COPY public.questions (question_id, question, answer, sample_id_id) FROM stdin;
\.


--
-- Data for Name: result_x_instrument; Type: TABLE DATA; Schema: public; Owner: decos
--

COPY public.result_x_instrument (x_id, instruments_id, results_id) FROM stdin;
\.


--
-- Data for Name: result_x_lab; Type: TABLE DATA; Schema: public; Owner: decos
--

COPY public.result_x_lab (x_id, lab_id, results_id) FROM stdin;
\.


--
-- Data for Name: result_x_sample; Type: TABLE DATA; Schema: public; Owner: decos
--

COPY public.result_x_sample (x_id, results_id, samples_id) FROM stdin;
4d45-adc3-f685a375d821_x_s_internal_00001	68a72f2e-6d5b-4d45-adc3-f685a375d821	s_internal_00001
4d45-adc3-f685a375d821_x_s_internal_00002	68a72f2e-6d5b-4d45-adc3-f685a375d821	s_internal_00002
\.


--
-- Data for Name: results; Type: TABLE DATA; Schema: public; Owner: decos
--

COPY public.results (result_id, main_repository, article_doi) FROM stdin;
68a72f2e-6d5b-4d45-adc3-f685a375d821	/result/01	10.2196/51021
\.


--
-- Data for Name: samples; Type: TABLE DATA; Schema: public; Owner: decos
--

COPY public.samples (sample_id, sample_short_description, sample_description, sample_feasibility, sample_status, sample_location, lab_id_id, sr_id_id) FROM stdin;
s_internal_00001	Test Title 01	TEST TEST TESST		Submitted	s_internal_00001_bad_sample/	LAGE	\N
s_internal_00002	New Title	New Life		Submitted	s_internal_00002_new_samples/	LAGE	\N
\.


--
-- Data for Name: service_requests; Type: TABLE DATA; Schema: public; Owner: decos
--

COPY public.service_requests (sr_id, sr_status, exp_description, output_delivery_date, lab_id_id, proposal_id_id) FROM stdin;
\.


--
-- Data for Name: steps; Type: TABLE DATA; Schema: public; Owner: decos
--

COPY public.steps (step_id, assigned_uoa, performed_uoa, eff_sample_date_of_delivery, eff_reagents_date_of_delivery, sample_quality, sample_quality_description, sample_quality_extra_budjet, instrument_id_id, sample_id_id, technique_id_id) FROM stdin;
\.


--
-- Data for Name: techniques; Type: TABLE DATA; Schema: public; Owner: decos
--

COPY public.techniques (technique_id, technique_name, description) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: decos
--

COPY public.users (user_id, name_surname, email, affiliation, gender, legal_status, research_role) FROM stdin;
admin	Marco Prenassi	admin@example.com	AREA	male	\N	technician
\.


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: decos
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 234, true);


--
-- Name: lab_x_instrument_id_seq; Type: SEQUENCE SET; Schema: public; Owner: decos
--

SELECT pg_catalog.setval('public.lab_x_instrument_id_seq', 1, false);


--
-- Name: PRP_CDM_app_experimentdatamanagementplan PRP_CDM_app_experimentdatamanagementplan_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public."PRP_CDM_app_experimentdatamanagementplan"
    ADD CONSTRAINT "PRP_CDM_app_experimentdatamanagementplan_pkey" PRIMARY KEY (experiment_dmp_id);


--
-- Name: administration administration_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.administration
    ADD CONSTRAINT administration_pkey PRIMARY KEY (sr_id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: experimentdmp_x_filesinfo experimentdmp_x_filesinfo_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.experimentdmp_x_filesinfo
    ADD CONSTRAINT experimentdmp_x_filesinfo_pkey PRIMARY KEY (x_id);


--
-- Name: experimentdmp_x_instrument experimentdmp_x_instrument_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.experimentdmp_x_instrument
    ADD CONSTRAINT experimentdmp_x_instrument_pkey PRIMARY KEY (x_id);


--
-- Name: experimentdmp_x_lab experimentdmp_x_lab_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.experimentdmp_x_lab
    ADD CONSTRAINT experimentdmp_x_lab_pkey PRIMARY KEY (x_id);


--
-- Name: experimentdmp_x_sample experimentdmp_x_sample_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.experimentdmp_x_sample
    ADD CONSTRAINT experimentdmp_x_sample_pkey PRIMARY KEY (x_id);


--
-- Name: fileinfo_x_lab fileinfo_x_lab_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.fileinfo_x_lab
    ADD CONSTRAINT fileinfo_x_lab_pkey PRIMARY KEY (x_id);


--
-- Name: filesinfo filesinfo_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.filesinfo
    ADD CONSTRAINT filesinfo_pkey PRIMARY KEY (file_info_id);


--
-- Name: instrument_x_technique instrument_x_technique_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.instrument_x_technique
    ADD CONSTRAINT instrument_x_technique_pkey PRIMARY KEY (x_id);


--
-- Name: instruments instruments_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.instruments
    ADD CONSTRAINT instruments_pkey PRIMARY KEY (instrument_id);


--
-- Name: lab_x_instrument lab_x_instrument_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.lab_x_instrument
    ADD CONSTRAINT lab_x_instrument_pkey PRIMARY KEY (id);


--
-- Name: labdmp labdmp_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.labdmp
    ADD CONSTRAINT labdmp_pkey PRIMARY KEY (lab_id);


--
-- Name: laboratories laboratories_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.laboratories
    ADD CONSTRAINT laboratories_pkey PRIMARY KEY (lab_id);


--
-- Name: lage_samples lage_samples_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.lage_samples
    ADD CONSTRAINT lage_samples_pkey PRIMARY KEY (samples_ptr_id);


--
-- Name: lame_samples lame_samples_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.lame_samples
    ADD CONSTRAINT lame_samples_pkey PRIMARY KEY (samples_ptr_id);


--
-- Name: proposals proposals_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.proposals
    ADD CONSTRAINT proposals_pkey PRIMARY KEY (proposal_id);


--
-- Name: questions questions_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT questions_pkey PRIMARY KEY (question_id);


--
-- Name: result_x_instrument result_x_instrument_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.result_x_instrument
    ADD CONSTRAINT result_x_instrument_pkey PRIMARY KEY (x_id);


--
-- Name: result_x_lab result_x_lab_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.result_x_lab
    ADD CONSTRAINT result_x_lab_pkey PRIMARY KEY (x_id);


--
-- Name: result_x_sample result_x_sample_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.result_x_sample
    ADD CONSTRAINT result_x_sample_pkey PRIMARY KEY (x_id);


--
-- Name: results results_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.results
    ADD CONSTRAINT results_pkey PRIMARY KEY (result_id);


--
-- Name: samples samples_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.samples
    ADD CONSTRAINT samples_pkey PRIMARY KEY (sample_id);


--
-- Name: service_requests service_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.service_requests
    ADD CONSTRAINT service_requests_pkey PRIMARY KEY (sr_id);


--
-- Name: steps steps_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.steps
    ADD CONSTRAINT steps_pkey PRIMARY KEY (step_id);


--
-- Name: techniques techniques_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.techniques
    ADD CONSTRAINT techniques_pkey PRIMARY KEY (technique_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: PRP_CDM_app_experimentda_experiment_dmp_id_309ba834_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX "PRP_CDM_app_experimentda_experiment_dmp_id_309ba834_like" ON public."PRP_CDM_app_experimentdatamanagementplan" USING btree (experiment_dmp_id varchar_pattern_ops);


--
-- Name: administration_sr_id_44c4faf2_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX administration_sr_id_44c4faf2_like ON public.administration USING btree (sr_id varchar_pattern_ops);


--
-- Name: experimentdmp_x_filesinfo_experimentdmp_id_150ca329; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX experimentdmp_x_filesinfo_experimentdmp_id_150ca329 ON public.experimentdmp_x_filesinfo USING btree (experimentdmp_id);


--
-- Name: experimentdmp_x_filesinfo_experimentdmp_id_150ca329_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX experimentdmp_x_filesinfo_experimentdmp_id_150ca329_like ON public.experimentdmp_x_filesinfo USING btree (experimentdmp_id varchar_pattern_ops);


--
-- Name: experimentdmp_x_filesinfo_file_info_id_f4c32e23; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX experimentdmp_x_filesinfo_file_info_id_f4c32e23 ON public.experimentdmp_x_filesinfo USING btree (file_info_id);


--
-- Name: experimentdmp_x_filesinfo_file_info_id_f4c32e23_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX experimentdmp_x_filesinfo_file_info_id_f4c32e23_like ON public.experimentdmp_x_filesinfo USING btree (file_info_id varchar_pattern_ops);


--
-- Name: experimentdmp_x_filesinfo_x_id_48ddcde1_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX experimentdmp_x_filesinfo_x_id_48ddcde1_like ON public.experimentdmp_x_filesinfo USING btree (x_id varchar_pattern_ops);


--
-- Name: experimentdmp_x_instrument_experimentdmp_id_83a4c1a9; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX experimentdmp_x_instrument_experimentdmp_id_83a4c1a9 ON public.experimentdmp_x_instrument USING btree (experimentdmp_id);


--
-- Name: experimentdmp_x_instrument_experimentdmp_id_83a4c1a9_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX experimentdmp_x_instrument_experimentdmp_id_83a4c1a9_like ON public.experimentdmp_x_instrument USING btree (experimentdmp_id varchar_pattern_ops);


--
-- Name: experimentdmp_x_instrument_instruments_id_e7e0b61d; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX experimentdmp_x_instrument_instruments_id_e7e0b61d ON public.experimentdmp_x_instrument USING btree (instruments_id);


--
-- Name: experimentdmp_x_instrument_instruments_id_e7e0b61d_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX experimentdmp_x_instrument_instruments_id_e7e0b61d_like ON public.experimentdmp_x_instrument USING btree (instruments_id varchar_pattern_ops);


--
-- Name: experimentdmp_x_instrument_x_id_22f88aee_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX experimentdmp_x_instrument_x_id_22f88aee_like ON public.experimentdmp_x_instrument USING btree (x_id varchar_pattern_ops);


--
-- Name: experimentdmp_x_lab_experimentdmp_id_a1d2979e; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX experimentdmp_x_lab_experimentdmp_id_a1d2979e ON public.experimentdmp_x_lab USING btree (experimentdmp_id);


--
-- Name: experimentdmp_x_lab_experimentdmp_id_a1d2979e_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX experimentdmp_x_lab_experimentdmp_id_a1d2979e_like ON public.experimentdmp_x_lab USING btree (experimentdmp_id varchar_pattern_ops);


--
-- Name: experimentdmp_x_lab_lab_id_5d4fea9a; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX experimentdmp_x_lab_lab_id_5d4fea9a ON public.experimentdmp_x_lab USING btree (lab_id);


--
-- Name: experimentdmp_x_lab_lab_id_5d4fea9a_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX experimentdmp_x_lab_lab_id_5d4fea9a_like ON public.experimentdmp_x_lab USING btree (lab_id varchar_pattern_ops);


--
-- Name: experimentdmp_x_lab_x_id_7f6e0710_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX experimentdmp_x_lab_x_id_7f6e0710_like ON public.experimentdmp_x_lab USING btree (x_id varchar_pattern_ops);


--
-- Name: experimentdmp_x_sample_experimentdmp_id_7abaab9d; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX experimentdmp_x_sample_experimentdmp_id_7abaab9d ON public.experimentdmp_x_sample USING btree (experimentdmp_id);


--
-- Name: experimentdmp_x_sample_experimentdmp_id_7abaab9d_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX experimentdmp_x_sample_experimentdmp_id_7abaab9d_like ON public.experimentdmp_x_sample USING btree (experimentdmp_id varchar_pattern_ops);


--
-- Name: experimentdmp_x_sample_samples_id_5419717c; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX experimentdmp_x_sample_samples_id_5419717c ON public.experimentdmp_x_sample USING btree (samples_id);


--
-- Name: experimentdmp_x_sample_samples_id_5419717c_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX experimentdmp_x_sample_samples_id_5419717c_like ON public.experimentdmp_x_sample USING btree (samples_id varchar_pattern_ops);


--
-- Name: experimentdmp_x_sample_x_id_27e95297_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX experimentdmp_x_sample_x_id_27e95297_like ON public.experimentdmp_x_sample USING btree (x_id varchar_pattern_ops);


--
-- Name: fileinfo_x_lab_file_info_id_1c31e5a2; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX fileinfo_x_lab_file_info_id_1c31e5a2 ON public.fileinfo_x_lab USING btree (file_info_id);


--
-- Name: fileinfo_x_lab_file_info_id_1c31e5a2_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX fileinfo_x_lab_file_info_id_1c31e5a2_like ON public.fileinfo_x_lab USING btree (file_info_id varchar_pattern_ops);


--
-- Name: fileinfo_x_lab_lab_id_3f11ea54; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX fileinfo_x_lab_lab_id_3f11ea54 ON public.fileinfo_x_lab USING btree (lab_id);


--
-- Name: fileinfo_x_lab_lab_id_3f11ea54_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX fileinfo_x_lab_lab_id_3f11ea54_like ON public.fileinfo_x_lab USING btree (lab_id varchar_pattern_ops);


--
-- Name: fileinfo_x_lab_x_id_7b0d6470_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX fileinfo_x_lab_x_id_7b0d6470_like ON public.fileinfo_x_lab USING btree (x_id varchar_pattern_ops);


--
-- Name: filesinfo_file_info_id_6bf51d88_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX filesinfo_file_info_id_6bf51d88_like ON public.filesinfo USING btree (file_info_id varchar_pattern_ops);


--
-- Name: instrument_x_technique_instrument_id_id_2775fa5a; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX instrument_x_technique_instrument_id_id_2775fa5a ON public.instrument_x_technique USING btree (instrument_id_id);


--
-- Name: instrument_x_technique_instrument_id_id_2775fa5a_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX instrument_x_technique_instrument_id_id_2775fa5a_like ON public.instrument_x_technique USING btree (instrument_id_id varchar_pattern_ops);


--
-- Name: instrument_x_technique_technique_id_id_67a1725a; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX instrument_x_technique_technique_id_id_67a1725a ON public.instrument_x_technique USING btree (technique_id_id);


--
-- Name: instrument_x_technique_technique_id_id_67a1725a_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX instrument_x_technique_technique_id_id_67a1725a_like ON public.instrument_x_technique USING btree (technique_id_id varchar_pattern_ops);


--
-- Name: instrument_x_technique_x_id_09847299_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX instrument_x_technique_x_id_09847299_like ON public.instrument_x_technique USING btree (x_id varchar_pattern_ops);


--
-- Name: instruments_instrument_id_99cd1132_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX instruments_instrument_id_99cd1132_like ON public.instruments USING btree (instrument_id varchar_pattern_ops);


--
-- Name: lab_x_instrument_instrument_id_id_61b2ee3a; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX lab_x_instrument_instrument_id_id_61b2ee3a ON public.lab_x_instrument USING btree (instrument_id_id);


--
-- Name: lab_x_instrument_instrument_id_id_61b2ee3a_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX lab_x_instrument_instrument_id_id_61b2ee3a_like ON public.lab_x_instrument USING btree (instrument_id_id varchar_pattern_ops);


--
-- Name: lab_x_instrument_lab_id_id_cf79aee8; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX lab_x_instrument_lab_id_id_cf79aee8 ON public.lab_x_instrument USING btree (lab_id_id);


--
-- Name: lab_x_instrument_lab_id_id_cf79aee8_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX lab_x_instrument_lab_id_id_cf79aee8_like ON public.lab_x_instrument USING btree (lab_id_id varchar_pattern_ops);


--
-- Name: labdmp_lab_id_5ca421c0_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX labdmp_lab_id_5ca421c0_like ON public.labdmp USING btree (lab_id varchar_pattern_ops);


--
-- Name: laboratories_lab_id_226b791e_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX laboratories_lab_id_226b791e_like ON public.laboratories USING btree (lab_id varchar_pattern_ops);


--
-- Name: lage_samples_samples_ptr_id_ee82f820_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX lage_samples_samples_ptr_id_ee82f820_like ON public.lage_samples USING btree (samples_ptr_id varchar_pattern_ops);


--
-- Name: lame_samples_samples_ptr_id_d6261525_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX lame_samples_samples_ptr_id_d6261525_like ON public.lame_samples USING btree (samples_ptr_id varchar_pattern_ops);


--
-- Name: proposals_proposal_id_6eff373c_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX proposals_proposal_id_6eff373c_like ON public.proposals USING btree (proposal_id varchar_pattern_ops);


--
-- Name: proposals_user_id_id_10217a25; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX proposals_user_id_id_10217a25 ON public.proposals USING btree (user_id_id);


--
-- Name: proposals_user_id_id_10217a25_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX proposals_user_id_id_10217a25_like ON public.proposals USING btree (user_id_id varchar_pattern_ops);


--
-- Name: questions_question_id_243ed5e8_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX questions_question_id_243ed5e8_like ON public.questions USING btree (question_id varchar_pattern_ops);


--
-- Name: questions_sample_id_id_f5a232cc; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX questions_sample_id_id_f5a232cc ON public.questions USING btree (sample_id_id);


--
-- Name: questions_sample_id_id_f5a232cc_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX questions_sample_id_id_f5a232cc_like ON public.questions USING btree (sample_id_id varchar_pattern_ops);


--
-- Name: result_x_instrument_instruments_id_0509acb5; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX result_x_instrument_instruments_id_0509acb5 ON public.result_x_instrument USING btree (instruments_id);


--
-- Name: result_x_instrument_instruments_id_0509acb5_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX result_x_instrument_instruments_id_0509acb5_like ON public.result_x_instrument USING btree (instruments_id varchar_pattern_ops);


--
-- Name: result_x_instrument_results_id_5c3a1af5; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX result_x_instrument_results_id_5c3a1af5 ON public.result_x_instrument USING btree (results_id);


--
-- Name: result_x_instrument_results_id_5c3a1af5_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX result_x_instrument_results_id_5c3a1af5_like ON public.result_x_instrument USING btree (results_id varchar_pattern_ops);


--
-- Name: result_x_instrument_x_id_4e558983_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX result_x_instrument_x_id_4e558983_like ON public.result_x_instrument USING btree (x_id varchar_pattern_ops);


--
-- Name: result_x_lab_lab_id_0abcc9b9; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX result_x_lab_lab_id_0abcc9b9 ON public.result_x_lab USING btree (lab_id);


--
-- Name: result_x_lab_lab_id_0abcc9b9_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX result_x_lab_lab_id_0abcc9b9_like ON public.result_x_lab USING btree (lab_id varchar_pattern_ops);


--
-- Name: result_x_lab_results_id_28a549a8; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX result_x_lab_results_id_28a549a8 ON public.result_x_lab USING btree (results_id);


--
-- Name: result_x_lab_results_id_28a549a8_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX result_x_lab_results_id_28a549a8_like ON public.result_x_lab USING btree (results_id varchar_pattern_ops);


--
-- Name: result_x_lab_x_id_6304725d_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX result_x_lab_x_id_6304725d_like ON public.result_x_lab USING btree (x_id varchar_pattern_ops);


--
-- Name: result_x_sample_results_id_21913027; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX result_x_sample_results_id_21913027 ON public.result_x_sample USING btree (results_id);


--
-- Name: result_x_sample_results_id_21913027_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX result_x_sample_results_id_21913027_like ON public.result_x_sample USING btree (results_id varchar_pattern_ops);


--
-- Name: result_x_sample_samples_id_96d0fe7c; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX result_x_sample_samples_id_96d0fe7c ON public.result_x_sample USING btree (samples_id);


--
-- Name: result_x_sample_samples_id_96d0fe7c_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX result_x_sample_samples_id_96d0fe7c_like ON public.result_x_sample USING btree (samples_id varchar_pattern_ops);


--
-- Name: result_x_sample_x_id_02e4be4b_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX result_x_sample_x_id_02e4be4b_like ON public.result_x_sample USING btree (x_id varchar_pattern_ops);


--
-- Name: results_result_id_8d59fa3b_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX results_result_id_8d59fa3b_like ON public.results USING btree (result_id varchar_pattern_ops);


--
-- Name: samples_lab_id_id_b8e10de9; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX samples_lab_id_id_b8e10de9 ON public.samples USING btree (lab_id_id);


--
-- Name: samples_lab_id_id_b8e10de9_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX samples_lab_id_id_b8e10de9_like ON public.samples USING btree (lab_id_id varchar_pattern_ops);


--
-- Name: samples_sample_id_da05c421_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX samples_sample_id_da05c421_like ON public.samples USING btree (sample_id varchar_pattern_ops);


--
-- Name: samples_sr_id_id_116929be; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX samples_sr_id_id_116929be ON public.samples USING btree (sr_id_id);


--
-- Name: samples_sr_id_id_116929be_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX samples_sr_id_id_116929be_like ON public.samples USING btree (sr_id_id varchar_pattern_ops);


--
-- Name: service_requests_lab_id_id_4e7a6467; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX service_requests_lab_id_id_4e7a6467 ON public.service_requests USING btree (lab_id_id);


--
-- Name: service_requests_lab_id_id_4e7a6467_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX service_requests_lab_id_id_4e7a6467_like ON public.service_requests USING btree (lab_id_id varchar_pattern_ops);


--
-- Name: service_requests_proposal_id_id_a61f0fa6; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX service_requests_proposal_id_id_a61f0fa6 ON public.service_requests USING btree (proposal_id_id);


--
-- Name: service_requests_proposal_id_id_a61f0fa6_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX service_requests_proposal_id_id_a61f0fa6_like ON public.service_requests USING btree (proposal_id_id varchar_pattern_ops);


--
-- Name: service_requests_sr_id_070fece8_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX service_requests_sr_id_070fece8_like ON public.service_requests USING btree (sr_id varchar_pattern_ops);


--
-- Name: steps_instrument_id_id_e9ada339; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX steps_instrument_id_id_e9ada339 ON public.steps USING btree (instrument_id_id);


--
-- Name: steps_instrument_id_id_e9ada339_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX steps_instrument_id_id_e9ada339_like ON public.steps USING btree (instrument_id_id varchar_pattern_ops);


--
-- Name: steps_sample_id_id_f11ebfd8; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX steps_sample_id_id_f11ebfd8 ON public.steps USING btree (sample_id_id);


--
-- Name: steps_sample_id_id_f11ebfd8_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX steps_sample_id_id_f11ebfd8_like ON public.steps USING btree (sample_id_id varchar_pattern_ops);


--
-- Name: steps_step_id_2299c1e5_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX steps_step_id_2299c1e5_like ON public.steps USING btree (step_id varchar_pattern_ops);


--
-- Name: steps_technique_id_id_79755905; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX steps_technique_id_id_79755905 ON public.steps USING btree (technique_id_id);


--
-- Name: steps_technique_id_id_79755905_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX steps_technique_id_id_79755905_like ON public.steps USING btree (technique_id_id varchar_pattern_ops);


--
-- Name: techniques_technique_id_56008478_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX techniques_technique_id_56008478_like ON public.techniques USING btree (technique_id varchar_pattern_ops);


--
-- Name: users_user_id_26693996_like; Type: INDEX; Schema: public; Owner: decos
--

CREATE INDEX users_user_id_26693996_like ON public.users USING btree (user_id varchar_pattern_ops);


--
-- Name: experimentdmp_x_filesinfo experimentdmp_x_file_experimentdmp_id_150ca329_fk_PRP_CDM_a; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.experimentdmp_x_filesinfo
    ADD CONSTRAINT "experimentdmp_x_file_experimentdmp_id_150ca329_fk_PRP_CDM_a" FOREIGN KEY (experimentdmp_id) REFERENCES public."PRP_CDM_app_experimentdatamanagementplan"(experiment_dmp_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: experimentdmp_x_filesinfo experimentdmp_x_file_file_info_id_f4c32e23_fk_filesinfo; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.experimentdmp_x_filesinfo
    ADD CONSTRAINT experimentdmp_x_file_file_info_id_f4c32e23_fk_filesinfo FOREIGN KEY (file_info_id) REFERENCES public.filesinfo(file_info_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: experimentdmp_x_instrument experimentdmp_x_inst_experimentdmp_id_83a4c1a9_fk_PRP_CDM_a; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.experimentdmp_x_instrument
    ADD CONSTRAINT "experimentdmp_x_inst_experimentdmp_id_83a4c1a9_fk_PRP_CDM_a" FOREIGN KEY (experimentdmp_id) REFERENCES public."PRP_CDM_app_experimentdatamanagementplan"(experiment_dmp_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: experimentdmp_x_instrument experimentdmp_x_inst_instruments_id_e7e0b61d_fk_instrumen; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.experimentdmp_x_instrument
    ADD CONSTRAINT experimentdmp_x_inst_instruments_id_e7e0b61d_fk_instrumen FOREIGN KEY (instruments_id) REFERENCES public.instruments(instrument_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: experimentdmp_x_lab experimentdmp_x_lab_experimentdmp_id_a1d2979e_fk_PRP_CDM_a; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.experimentdmp_x_lab
    ADD CONSTRAINT "experimentdmp_x_lab_experimentdmp_id_a1d2979e_fk_PRP_CDM_a" FOREIGN KEY (experimentdmp_id) REFERENCES public."PRP_CDM_app_experimentdatamanagementplan"(experiment_dmp_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: experimentdmp_x_lab experimentdmp_x_lab_lab_id_5d4fea9a_fk_laboratories_lab_id; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.experimentdmp_x_lab
    ADD CONSTRAINT experimentdmp_x_lab_lab_id_5d4fea9a_fk_laboratories_lab_id FOREIGN KEY (lab_id) REFERENCES public.laboratories(lab_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: experimentdmp_x_sample experimentdmp_x_samp_experimentdmp_id_7abaab9d_fk_PRP_CDM_a; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.experimentdmp_x_sample
    ADD CONSTRAINT "experimentdmp_x_samp_experimentdmp_id_7abaab9d_fk_PRP_CDM_a" FOREIGN KEY (experimentdmp_id) REFERENCES public."PRP_CDM_app_experimentdatamanagementplan"(experiment_dmp_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: experimentdmp_x_sample experimentdmp_x_sample_samples_id_5419717c_fk_samples_sample_id; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.experimentdmp_x_sample
    ADD CONSTRAINT experimentdmp_x_sample_samples_id_5419717c_fk_samples_sample_id FOREIGN KEY (samples_id) REFERENCES public.samples(sample_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: fileinfo_x_lab fileinfo_x_lab_file_info_id_1c31e5a2_fk_filesinfo_file_info_id; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.fileinfo_x_lab
    ADD CONSTRAINT fileinfo_x_lab_file_info_id_1c31e5a2_fk_filesinfo_file_info_id FOREIGN KEY (file_info_id) REFERENCES public.filesinfo(file_info_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: fileinfo_x_lab fileinfo_x_lab_lab_id_3f11ea54_fk_laboratories_lab_id; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.fileinfo_x_lab
    ADD CONSTRAINT fileinfo_x_lab_lab_id_3f11ea54_fk_laboratories_lab_id FOREIGN KEY (lab_id) REFERENCES public.laboratories(lab_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: instrument_x_technique instrument_x_techniq_instrument_id_id_2775fa5a_fk_instrumen; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.instrument_x_technique
    ADD CONSTRAINT instrument_x_techniq_instrument_id_id_2775fa5a_fk_instrumen FOREIGN KEY (instrument_id_id) REFERENCES public.instruments(instrument_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: instrument_x_technique instrument_x_techniq_technique_id_id_67a1725a_fk_technique; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.instrument_x_technique
    ADD CONSTRAINT instrument_x_techniq_technique_id_id_67a1725a_fk_technique FOREIGN KEY (technique_id_id) REFERENCES public.techniques(technique_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: lab_x_instrument lab_x_instrument_instrument_id_id_61b2ee3a_fk_instrumen; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.lab_x_instrument
    ADD CONSTRAINT lab_x_instrument_instrument_id_id_61b2ee3a_fk_instrumen FOREIGN KEY (instrument_id_id) REFERENCES public.instruments(instrument_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: lab_x_instrument lab_x_instrument_lab_id_id_cf79aee8_fk_laboratories_lab_id; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.lab_x_instrument
    ADD CONSTRAINT lab_x_instrument_lab_id_id_cf79aee8_fk_laboratories_lab_id FOREIGN KEY (lab_id_id) REFERENCES public.laboratories(lab_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: lage_samples lage_samples_samples_ptr_id_ee82f820_fk_samples_sample_id; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.lage_samples
    ADD CONSTRAINT lage_samples_samples_ptr_id_ee82f820_fk_samples_sample_id FOREIGN KEY (samples_ptr_id) REFERENCES public.samples(sample_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: lame_samples lame_samples_samples_ptr_id_d6261525_fk_samples_sample_id; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.lame_samples
    ADD CONSTRAINT lame_samples_samples_ptr_id_d6261525_fk_samples_sample_id FOREIGN KEY (samples_ptr_id) REFERENCES public.samples(sample_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: proposals proposals_user_id_id_10217a25_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.proposals
    ADD CONSTRAINT proposals_user_id_id_10217a25_fk_users_user_id FOREIGN KEY (user_id_id) REFERENCES public.users(user_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: questions questions_sample_id_id_f5a232cc_fk_samples_sample_id; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT questions_sample_id_id_f5a232cc_fk_samples_sample_id FOREIGN KEY (sample_id_id) REFERENCES public.samples(sample_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: result_x_instrument result_x_instrument_instruments_id_0509acb5_fk_instrumen; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.result_x_instrument
    ADD CONSTRAINT result_x_instrument_instruments_id_0509acb5_fk_instrumen FOREIGN KEY (instruments_id) REFERENCES public.instruments(instrument_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: result_x_instrument result_x_instrument_results_id_5c3a1af5_fk_results_result_id; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.result_x_instrument
    ADD CONSTRAINT result_x_instrument_results_id_5c3a1af5_fk_results_result_id FOREIGN KEY (results_id) REFERENCES public.results(result_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: result_x_lab result_x_lab_lab_id_0abcc9b9_fk_laboratories_lab_id; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.result_x_lab
    ADD CONSTRAINT result_x_lab_lab_id_0abcc9b9_fk_laboratories_lab_id FOREIGN KEY (lab_id) REFERENCES public.laboratories(lab_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: result_x_lab result_x_lab_results_id_28a549a8_fk_results_result_id; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.result_x_lab
    ADD CONSTRAINT result_x_lab_results_id_28a549a8_fk_results_result_id FOREIGN KEY (results_id) REFERENCES public.results(result_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: result_x_sample result_x_sample_results_id_21913027_fk_results_result_id; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.result_x_sample
    ADD CONSTRAINT result_x_sample_results_id_21913027_fk_results_result_id FOREIGN KEY (results_id) REFERENCES public.results(result_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: result_x_sample result_x_sample_samples_id_96d0fe7c_fk_samples_sample_id; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.result_x_sample
    ADD CONSTRAINT result_x_sample_samples_id_96d0fe7c_fk_samples_sample_id FOREIGN KEY (samples_id) REFERENCES public.samples(sample_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: samples samples_lab_id_id_b8e10de9_fk_laboratories_lab_id; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.samples
    ADD CONSTRAINT samples_lab_id_id_b8e10de9_fk_laboratories_lab_id FOREIGN KEY (lab_id_id) REFERENCES public.laboratories(lab_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: samples samples_sr_id_id_116929be_fk_service_requests_sr_id; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.samples
    ADD CONSTRAINT samples_sr_id_id_116929be_fk_service_requests_sr_id FOREIGN KEY (sr_id_id) REFERENCES public.service_requests(sr_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: service_requests service_requests_lab_id_id_4e7a6467_fk_laboratories_lab_id; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.service_requests
    ADD CONSTRAINT service_requests_lab_id_id_4e7a6467_fk_laboratories_lab_id FOREIGN KEY (lab_id_id) REFERENCES public.laboratories(lab_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: service_requests service_requests_proposal_id_id_a61f0fa6_fk_proposals; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.service_requests
    ADD CONSTRAINT service_requests_proposal_id_id_a61f0fa6_fk_proposals FOREIGN KEY (proposal_id_id) REFERENCES public.proposals(proposal_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: steps steps_instrument_id_id_e9ada339_fk_instruments_instrument_id; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.steps
    ADD CONSTRAINT steps_instrument_id_id_e9ada339_fk_instruments_instrument_id FOREIGN KEY (instrument_id_id) REFERENCES public.instruments(instrument_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: steps steps_sample_id_id_f11ebfd8_fk_samples_sample_id; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.steps
    ADD CONSTRAINT steps_sample_id_id_f11ebfd8_fk_samples_sample_id FOREIGN KEY (sample_id_id) REFERENCES public.samples(sample_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: steps steps_technique_id_id_79755905_fk_techniques_technique_id; Type: FK CONSTRAINT; Schema: public; Owner: decos
--

ALTER TABLE ONLY public.steps
    ADD CONSTRAINT steps_technique_id_id_79755905_fk_techniques_technique_id FOREIGN KEY (technique_id_id) REFERENCES public.techniques(technique_id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

