version: "3.9"

services:
  webapp:
    container_name: ${WEBAPP_CONTAINER:-decos_webapp}
    image: decos_webapp
    build:
      context: .
      dockerfile: ./decos/Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && cat /app/decos/decos_webapp/APIs/decos_minio_API/ca.pem >> /usr/local/lib/python3.12/site-packages/certifi/cacert.pem && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:${DEBUGPY_PORT:-5678} decos/decos_webapp/manage.py runserver 0.0.0.0:${WEB_APP_PORT:-8080}"]
    env_file:
      - .env.dev
    environment:
      DECOS_SECRET_KEY_FILE: /run/secrets/decos_secret_key
      SUPERUSER_PASSWORD_FILE: /run/secrets/superuser_password
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      AUTHENTIK_SECRETS: /run/secrets/authentik_secret
      MINIO_SECRET_KEY_FILE: /run/secrets/minio_secret
    secrets:
      - source: decos_secret_key
        target: decos_secret_key
      - source: superuser_password
        target: superuser_password
      - source: postgres_password
        target: postgres_password
      - source: authentik_secret
        target: authentik_secret
      - source: minio_secret
        target: minio_secret

    ports:
      - "8080:8080"
      - "5678:5678"
    volumes:
      - .:/app
    user: "root:root"
    depends_on:
      - db

  db:
    container_name: ${DB_CONTAINER:-decos_db}
    image: decos_postgres_db
    build:
      context: .
      dockerfile: ./postgres-multiple-db/Dockerfile
    env_file:
      - .env.dev
    environment:
      POSTGRES_MULTIPLE_DATABASES: ${POSTGRES_WEBAPP_DB:-decos_webapp_db}, ${POSTGRES_METADATA_DB:-decos_metadata_db}
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - source: postgres_password
        target: postgres_password
    volumes:
      - default_pg_data:/var/lib/postgresql/data/
      - ./backups:/backups

volumes:
  default_pg_data:
    name: ${POSTGRES_VOLUME:-postgres_data_dev}

secrets:
  decos_secret_key:
    file: ${DECOS_SECRET_KEY_HOST_FILE:-.secrets/decos_secret_key.txt}
  superuser_password:
    file: ${SUPERUSER_PASSWORD_HOST_FILE:-.secrets/superuser_password.txt}
  postgres_password:
    file: ${POSTGRES_PASSWORD_HOST_FILE:-.secrets/postgres_password.txt}
  authentik_secret:
    file: ${AUTHENTIK_SECRET_HOST_FILE:-.secrets/authentik_secret.txt}
  minio_secret:
    file: ${MINIO_SECRET_HOST_FILE:-.secrets/minio_secret.txt}