# Generated by Django 5.2.3 on 2025-07-10 08:56

import PRP_CDM_app.models.common_data_model
import PRP_CDM_app.models.laboratory_models.bio_open_lab_unisalento
import PRP_CDM_app.models.laboratory_models.lage
import PRP_CDM_app.models.laboratory_models.lame
import PRP_CDM_app.models.laboratory_models.nanoinnovation_laboratory
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('sr_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('lab_id', models.CharField(max_length=50)),
                ('dmptitle', models.CharField(blank=True, max_length=128)),
                ('user_id', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=128)),
                ('affiliation', models.CharField(blank=True, max_length=128)),
                ('experimentabstract', models.TextField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'administration',
            },
        ),
        migrations.CreateModel(
            name='Samples',
            fields=[
                ('sample_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sample_short_description', models.CharField(max_length=64)),
                ('sample_description', models.TextField(blank=True, max_length=500)),
                ('sample_feasibility', models.CharField(blank=True, choices=[('feasible', 'feasible'), ('not feasible', 'not feasible'), ('feasible with reservations', 'feasible with reservations')])),
                ('sample_status', models.CharField(default='Submitted')),
                ('sample_location', models.CharField(blank=True, null=True)),
                ('sensible_data', models.BooleanField(blank=True)),
            ],
            options={
                'db_table': 'samples',
            },
        ),
        migrations.CreateModel(
            name='ExperimentDMP',
            fields=[
                ('experiment_dmp_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('experiment_title', models.CharField(max_length=255)),
                ('principal_investigator', models.CharField(max_length=255)),
                ('affiliated_institutions', models.TextField()),
                ('project_acronym', models.CharField(blank=True, max_length=100, null=True)),
                ('grant_number', models.CharField(blank=True, max_length=100, null=True)),
                ('plan_creation_date', models.DateField()),
                ('funding_programme', models.CharField(blank=True, max_length=255, null=True)),
                ('collaborators_roles', models.TextField(blank=True, null=True)),
                ('ethics_approvals', models.TextField(blank=True, null=True)),
                ('roles_responsibilities', models.TextField(blank=True, null=True)),
                ('estimated_costs', models.TextField(blank=True, null=True)),
                ('infrastructure_support', models.TextField(blank=True, null=True)),
                ('public_dataset', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'experiment_dmp',
            },
        ),
        migrations.CreateModel(
            name='Instruments',
            fields=[
                ('instrument_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('vendor', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'instruments',
            },
        ),
        migrations.CreateModel(
            name='labDMP',
            fields=[
                ('lab_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50)),
                ('data_curator', models.CharField(max_length=128)),
                ('instrument_metadata_collection', models.CharField(blank=True, max_length=128)),
                ('additional_enotebook_open_collection', models.CharField(blank=True, max_length=128)),
                ('sample_standard', models.CharField(blank=True, max_length=128)),
                ('metadata_schema_defined', models.CharField(blank=True)),
                ('backup_policy_published_data', models.CharField(blank=True)),
                ('backup_policy_unplublished_data', models.CharField(blank=True)),
            ],
            options={
                'db_table': 'labdmp',
            },
        ),
        migrations.CreateModel(
            name='Laboratories',
            fields=[
                ('lab_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'laboratories',
            },
        ),
        migrations.CreateModel(
            name='Proposals',
            fields=[
                ('proposal_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('proposal_status', models.CharField(default='Submitted')),
                ('proposal_feasibility', models.CharField(blank=True, choices=[('feasible', 'feasible'), ('not feasible', 'not feasible'), ('feasible with reservations', 'feasible with reservations')])),
                ('proposal_date', models.DateField(default=datetime.date.today)),
                ('proposal_filename', models.FileField(blank=True, upload_to=PRP_CDM_app.models.common_data_model.Proposals.user_directory_path)),
            ],
            options={
                'db_table': 'proposals',
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('result_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('main_repository', models.CharField(blank=True, max_length=2048)),
                ('article_doi', models.CharField(blank=True, max_length=256)),
                ('publication_title', models.CharField(blank=True, max_length=512)),
                ('authors', models.TextField(blank=True)),
                ('journal_name', models.CharField(blank=True, max_length=256)),
                ('publication_year', models.PositiveIntegerField(blank=True, null=True)),
                ('open_trusted_repo_published_data', models.BooleanField(blank=True)),
                ('open_data_licence', models.CharField(blank=True)),
                ('open_access_journal_publication', models.BooleanField(blank=True)),
                ('clear_data_provenance', models.BooleanField(blank=True)),
                ('related_data_open', models.BooleanField(blank=True)),
                ('licence_scientific_documents', models.BooleanField(blank=True)),
                ('raw_data_storage_location', models.CharField(blank=True)),
                ('raw_data_storage_time_retention', models.CharField(blank=True)),
            ],
            options={
                'db_table': 'results',
            },
        ),
        migrations.CreateModel(
            name='Techniques',
            fields=[
                ('technique_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('technique_name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'techniques',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name_surname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=128)),
                ('affiliation', models.CharField(max_length=128)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')])),
                ('legal_status', models.CharField(blank=True, choices=[('OTH', 'OTH'), ('PRV', 'PRV'), ('RES', 'RES'), ('SME', 'SME'), ('UNI', 'UNI')], null=True)),
                ('research_role', models.CharField(choices=[('senior scientist', 'senior scientist'), ('phd student', 'phd student'), ('professor / scientific coordinator', 'professor / scientific coordinator'), ('scientist', 'scientist'), ('manager', 'manager'), ('degree student', 'degree student'), ('post-doc', 'post-doc'), ('technician', 'technician'), ('other', 'other')])),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Bio_Open_Lab_UnisalentoSamples',
            fields=[
                ('samples_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PRP_CDM_app.samples')),
                ('sample_name', models.CharField(max_length=255)),
                ('sample_producer', models.CharField(max_length=255)),
                ('affiliation', models.CharField(max_length=255)),
                ('sample_purpose', models.CharField(blank=True)),
                ('sample_type', models.CharField(blank=True)),
                ('component_name', models.CharField(max_length=255)),
                ('component_chemical_formula', models.CharField(max_length=255)),
                ('sheet', models.CharField(blank=True)),
                ('layer', models.CharField(blank=True)),
                ('colloidal_solution', models.CharField(max_length=255)),
                ('sample_expiration_date', models.DateField(blank=True, null=True)),
                ('additional_filename', models.FileField(blank=True, upload_to=PRP_CDM_app.models.laboratory_models.bio_open_lab_unisalento.Bio_Open_Lab_UnisalentoSamples.user_directory_path)),
            ],
            options={
                'db_table': 'bioopenlabunisalento_samples',
            },
            bases=('PRP_CDM_app.samples',),
        ),
        migrations.CreateModel(
            name='LageSamples',
            fields=[
                ('samples_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PRP_CDM_app.samples')),
                ('type', models.CharField(blank=True)),
                ('is_volume_in_ul', models.CharField(blank=True)),
                ('is_buffer_used', models.CharField(blank=True)),
                ('is_quality', models.CharField(blank=True)),
                ('sample_date_of_delivery', models.DateField()),
                ('sample_back', models.BooleanField()),
                ('reagents_provided_by_client', models.BooleanField()),
                ('reagents_date_of_delivery', models.DateField(blank=True, null=True)),
                ('sample_sheet_filename', models.FileField(blank=True, upload_to=PRP_CDM_app.models.laboratory_models.lage.LageSamples.user_directory_path)),
                ('additional_filename', models.FileField(blank=True, upload_to=PRP_CDM_app.models.laboratory_models.lage.LageSamples.user_directory_path)),
            ],
            options={
                'db_table': 'lage_samples',
            },
            bases=('PRP_CDM_app.samples',),
        ),
        migrations.CreateModel(
            name='LameSamples',
            fields=[
                ('samples_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PRP_CDM_app.samples')),
                ('chemical_formula', models.CharField(blank=True)),
                ('elements_list', models.CharField(blank=True)),
                ('sample_date_of_delivery', models.DateField()),
                ('sample_back', models.BooleanField()),
                ('sample_sheet_filename', models.FileField(blank=True, upload_to=PRP_CDM_app.models.laboratory_models.lame.LameSamples.user_directory_path)),
                ('additional_filename', models.FileField(blank=True, upload_to=PRP_CDM_app.models.laboratory_models.lame.LameSamples.user_directory_path)),
            ],
            options={
                'db_table': 'lame_samples',
            },
            bases=('PRP_CDM_app.samples',),
        ),
        migrations.CreateModel(
            name='Nanoinnovation_LaboratorySamples',
            fields=[
                ('samples_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PRP_CDM_app.samples')),
                ('type', models.CharField(blank=True, max_length=64)),
                ('fixed', models.BooleanField(blank=True, null=True)),
                ('fixation_methods', models.TextField(blank=True)),
                ('support_material', models.CharField(blank=True, max_length=256)),
                ('support_measures', models.CharField(blank=True, max_length=128)),
                ('adherent_or_suspended', models.CharField(blank=True, choices=[('adherent', 'Adherent'), ('suspended', 'Suspended')], max_length=10)),
                ('other_info', models.TextField(blank=True)),
                ('origin_animal_vegetal', models.CharField(blank=True, max_length=128)),
                ('embedding_medium', models.CharField(blank=True, max_length=128)),
                ('slice_thickness_um', models.CharField(blank=True, max_length=32)),
                ('ethics_note_tissue', models.TextField(blank=True)),
                ('cell_origin', models.CharField(blank=True, max_length=128)),
                ('bsl', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('buffer_medium', models.CharField(blank=True, max_length=128)),
                ('ethics_note_cells', models.TextField(blank=True)),
                ('bacteria_origin', models.CharField(blank=True, max_length=128)),
                ('culture_medium_bacteria', models.CharField(blank=True, max_length=128)),
                ('virus_family', models.CharField(blank=True, max_length=128)),
                ('culture_medium_virus', models.CharField(blank=True, max_length=128)),
                ('is_powder_mixture', models.BooleanField(blank=True, null=True)),
                ('powder_chemical_name', models.CharField(blank=True, max_length=128)),
                ('powder_cas_number', models.CharField(blank=True, max_length=64)),
                ('powder_form', models.CharField(blank=True, choices=[('crystals', 'Crystals'), ('amorphous', 'Amorphous')], max_length=32)),
                ('powder_hazard', models.TextField(blank=True)),
                ('film_thickness_nm', models.CharField(blank=True, max_length=64)),
                ('is_film_mixture', models.BooleanField(blank=True, null=True)),
                ('film_chemical_name', models.CharField(blank=True, max_length=128)),
                ('film_cas_number', models.CharField(blank=True, max_length=64)),
                ('film_hazard', models.TextField(blank=True)),
                ('thin_film_type', models.CharField(blank=True, choices=[('supported', 'Supported'), ('self_standing', 'Self-standing')], max_length=32)),
                ('slice_origin', models.CharField(blank=True, max_length=128)),
                ('slice_standing', models.CharField(blank=True, choices=[('supported', 'Supported'), ('free', 'Free standing')], max_length=16)),
                ('polishing', models.BooleanField(blank=True, null=True)),
                ('polishing_grit', models.CharField(blank=True, max_length=64)),
                ('is_gel_mixture', models.BooleanField(blank=True, null=True)),
                ('gel_chemical_name', models.CharField(blank=True, max_length=128)),
                ('gel_cas_number', models.CharField(blank=True, max_length=64)),
                ('gel_hazard', models.TextField(blank=True)),
                ('gel_stiffness_roughness', models.CharField(blank=True, max_length=128)),
                ('is_solid_mixture', models.BooleanField(blank=True, null=True)),
                ('solid_chemical_name', models.CharField(blank=True, max_length=128)),
                ('solid_cas_number', models.CharField(blank=True, max_length=64)),
                ('solid_hazard', models.TextField(blank=True)),
                ('other_description', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('sample_sheet_filename', models.FileField(blank=True, upload_to=PRP_CDM_app.models.laboratory_models.nanoinnovation_laboratory.Nanoinnovation_LaboratorySamples.user_directory_path)),
                ('additional_filename', models.FileField(blank=True, upload_to=PRP_CDM_app.models.laboratory_models.nanoinnovation_laboratory.Nanoinnovation_LaboratorySamples.user_directory_path)),
            ],
            options={
                'db_table': 'nanoinnovation_laboratory_samples',
            },
            bases=('PRP_CDM_app.samples',),
        ),
        migrations.CreateModel(
            name='Bio_Open_Lab_UnisalentoMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata_id', models.CharField(max_length=64, unique=True)),
                ('device_name', models.CharField(blank=True, max_length=255, null=True)),
                ('formatted_voltage', models.CharField(blank=True, max_length=50, null=True)),
                ('exposure_s', models.FloatField(blank=True, null=True)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('acquisition_time', models.FloatField(blank=True, null=True)),
                ('formatted_indicated_mag', models.CharField(blank=True, max_length=50, null=True)),
                ('pixel_size_um', models.JSONField(blank=True, null=True)),
                ('pixel_depth', models.IntegerField(blank=True, null=True)),
                ('stage_alpha', models.CharField(blank=True, max_length=50, null=True)),
                ('stage_beta', models.CharField(blank=True, max_length=50, null=True)),
                ('stage_x', models.CharField(blank=True, max_length=50, null=True)),
                ('stage_y', models.CharField(blank=True, max_length=50, null=True)),
                ('stage_z', models.CharField(blank=True, max_length=50, null=True)),
                ('active_size_pixels', models.JSONField(blank=True, null=True)),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PRP_CDM_app.samples')),
            ],
            options={
                'db_table': 'bio_open_lab_unisalentometadata',
            },
        ),
        migrations.CreateModel(
            name='ExperimentDMPxSample',
            fields=[
                ('x_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('experiment_dmp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRP_CDM_app.experimentdmp')),
                ('samples', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRP_CDM_app.samples')),
            ],
            options={
                'db_table': 'experiment_dmp_x_sample',
            },
        ),
        migrations.AddField(
            model_name='experimentdmp',
            name='samples',
            field=models.ManyToManyField(through='PRP_CDM_app.ExperimentDMPxSample', to='PRP_CDM_app.samples'),
        ),
        migrations.CreateModel(
            name='ExperimentDMPxInstrument',
            fields=[
                ('x_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('experiment_dmp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRP_CDM_app.experimentdmp')),
                ('instruments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRP_CDM_app.instruments')),
            ],
            options={
                'db_table': 'experiment_dmp_x_instrument',
            },
        ),
        migrations.AddField(
            model_name='experimentdmp',
            name='instruments',
            field=models.ManyToManyField(through='PRP_CDM_app.ExperimentDMPxInstrument', to='PRP_CDM_app.instruments'),
        ),
        migrations.AddField(
            model_name='samples',
            name='lab_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PRP_CDM_app.laboratories'),
        ),
        migrations.CreateModel(
            name='ExperimentDMPxLab',
            fields=[
                ('x_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('experiment_dmp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRP_CDM_app.experimentdmp')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRP_CDM_app.laboratories')),
            ],
            options={
                'db_table': 'experiment_dmp_x_lab',
            },
        ),
        migrations.AddField(
            model_name='experimentdmp',
            name='lab',
            field=models.ManyToManyField(through='PRP_CDM_app.ExperimentDMPxLab', to='PRP_CDM_app.laboratories'),
        ),
        migrations.CreateModel(
            name='LabXInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_labs', to='PRP_CDM_app.instruments')),
                ('lab_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_instruments', to='PRP_CDM_app.laboratories')),
            ],
            options={
                'db_table': 'lab_x_instrument',
            },
        ),
        migrations.AddField(
            model_name='instruments',
            name='labs',
            field=models.ManyToManyField(through='PRP_CDM_app.LabXInstrument', to='PRP_CDM_app.laboratories'),
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('question_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('question', models.TextField(blank=True, max_length=500)),
                ('answer', models.TextField(blank=True, max_length=500)),
                ('sample_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PRP_CDM_app.samples')),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='ResultxExperimentDMP',
            fields=[
                ('x_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('experiment_dmp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRP_CDM_app.experimentdmp')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRP_CDM_app.results')),
            ],
            options={
                'db_table': 'result_x_experiment_dmp',
            },
        ),
        migrations.AddField(
            model_name='results',
            name='experiment_dmps',
            field=models.ManyToManyField(through='PRP_CDM_app.ResultxExperimentDMP', to='PRP_CDM_app.experimentdmp'),
        ),
        migrations.CreateModel(
            name='ResultxLaboratories',
            fields=[
                ('x_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRP_CDM_app.laboratories')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRP_CDM_app.results')),
            ],
            options={
                'db_table': 'result_x_laboratories',
            },
        ),
        migrations.AddField(
            model_name='results',
            name='lab',
            field=models.ManyToManyField(through='PRP_CDM_app.ResultxLaboratories', to='PRP_CDM_app.laboratories'),
        ),
        migrations.CreateModel(
            name='ServiceRequests',
            fields=[
                ('sr_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sr_status', models.CharField(default='Submitted')),
                ('exp_description', models.TextField(blank=True, max_length=500)),
                ('output_delivery_date', models.DateField(blank=True)),
                ('lab_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PRP_CDM_app.laboratories')),
                ('proposal_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PRP_CDM_app.proposals')),
            ],
            options={
                'db_table': 'service_requests',
            },
        ),
        migrations.AddField(
            model_name='samples',
            name='sr_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='PRP_CDM_app.servicerequests'),
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('step_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('assigned_uoa', models.IntegerField()),
                ('performed_uoa', models.IntegerField(default=0)),
                ('eff_sample_date_of_delivery', models.DateField()),
                ('eff_reagents_date_of_delivery', models.DateField()),
                ('sample_quality', models.CharField(blank=True)),
                ('sample_quality_description', models.TextField(blank=True, max_length=500)),
                ('sample_quality_extra_budjet', models.BooleanField(blank=True)),
                ('instrument_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PRP_CDM_app.instruments')),
                ('sample_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PRP_CDM_app.samples')),
                ('technique_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PRP_CDM_app.techniques')),
            ],
            options={
                'db_table': 'steps',
            },
        ),
        migrations.CreateModel(
            name='InstrumentXTechnique',
            fields=[
                ('x_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('instrument_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRP_CDM_app.instruments')),
                ('technique_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRP_CDM_app.techniques')),
            ],
            options={
                'db_table': 'instrument_x_technique',
            },
        ),
        migrations.AddField(
            model_name='proposals',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PRP_CDM_app.users'),
        ),
    ]
