# Generated by Django 5.1.7 on 2025-04-08 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentDMP',
            fields=[
                ('experiment_dmp_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('main_repository', models.CharField(blank=True, max_length=512)),
                ('article_doi', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'db_table': 'experiment_dmp',
            },
        ),
        migrations.CreateModel(
            name='ExperimentDMPxInstrument',
            fields=[
                ('x_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('experiment_dmp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PRP_CDM_app.experimentdmp')),
                ('instruments', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PRP_CDM_app.instruments')),
            ],
            options={
                'db_table': 'experiment_dmp_x_instrument',
            },
        ),
        migrations.CreateModel(
            name='ExperimentDMPxLab',
            fields=[
                ('x_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('experiment_dmp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PRP_CDM_app.experimentdmp')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PRP_CDM_app.laboratories')),
            ],
            options={
                'db_table': 'experiment_dmp_x_lab',
            },
        ),
        migrations.CreateModel(
            name='ExperimentDMPxSample',
            fields=[
                ('x_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('experiment_dmp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PRP_CDM_app.experimentdmp')),
                ('samples', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PRP_CDM_app.samples')),
            ],
            options={
                'db_table': 'experiment_dmp_x_sample',
            },
        ),
    ]
