# Generated by Django 5.2.4 on 2025-07-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nanoinnovation_laboratorysamples',
            name='bacteria_origin',
        ),
        migrations.RemoveField(
            model_name='nanoinnovation_laboratorysamples',
            name='bsl',
        ),
        migrations.RemoveField(
            model_name='nanoinnovation_laboratorysamples',
            name='cell_origin',
        ),
        migrations.RemoveField(
            model_name='nanoinnovation_laboratorysamples',
            name='culture_medium_bacteria',
        ),
        migrations.RemoveField(
            model_name='nanoinnovation_laboratorysamples',
            name='culture_medium_virus',
        ),
        migrations.RemoveField(
            model_name='nanoinnovation_laboratorysamples',
            name='ethics_note_cells',
        ),
        migrations.RemoveField(
            model_name='nanoinnovation_laboratorysamples',
            name='ethics_note_tissue',
        ),
        migrations.RemoveField(
            model_name='nanoinnovation_laboratorysamples',
            name='film_cas_number',
        ),
        migrations.RemoveField(
            model_name='nanoinnovation_laboratorysamples',
            name='film_chemical_name',
        ),
        migrations.RemoveField(
            model_name='nanoinnovation_laboratorysamples',
            name='film_hazard',
        ),
        migrations.RemoveField(
            model_name='nanoinnovation_laboratorysamples',
            name='film_thickness_nm',
        ),
        migrations.RemoveField(
            model_name='nanoinnovation_laboratorysamples',
            name='fixation_methods',
        ),
        migrations.RemoveField(
            model_name='nanoinnovation_laboratorysamples',
            name='fixed',
        ),
        migrations.RemoveField(
            model_name='nanoinnovation_laboratorysamples',
            name='gel_cas_number',
        ),
        migrations.RemoveField(
            model_name='nanoinnovation_laboratorysamples',
            name='gel_chemical_name',
        ),
        migrations.RemoveField(
            model_name='nanoinnovation_laboratorysamples',
            name='gel_hazard',
        ),
        migrations.RemoveField(
            model_name='nanoinnovation_laboratorysamples',
            name='gel_stiffness_roughness',
        ),
        migrations.RemoveField(
            model_name='nanoinnovation_laboratorysamples',
            name='is_film_mixture',
        ),
        migrations.RemoveField(
            model_name='nanoinnovation_laboratorysamples',
            name='is_gel_mixture',
        ),
        migrations.RemoveField(
            model_name='nanoinnovation_laboratorysamples',
            name='is_powder_mixture',
        ),
        migrations.RemoveField(
            model_name='nanoinnovation_laboratorysamples',
            name='is_solid_mixture',
        ),
        migrations.RemoveField(
            model_name='nanoinnovation_laboratorysamples',
            name='origin_animal_vegetal',
        ),
        migrations.RemoveField(
            model_name='nanoinnovation_laboratorysamples',
            name='other_description',
        ),
        migrations.RemoveField(
            model_name='nanoinnovation_laboratorysamples',
            name='other_info',
        ),
        migrations.RemoveField(
            model_name='nanoinnovation_laboratorysamples',
            name='polishing',
        ),
        migrations.RemoveField(
            model_name='nanoinnovation_laboratorysamples',
            name='polishing_grit',
        ),
        migrations.RemoveField(
            model_name='nanoinnovation_laboratorysamples',
            name='powder_cas_number',
        ),
        migrations.RemoveField(
            model_name='nanoinnovation_laboratorysamples',
            name='powder_chemical_name',
        ),
        migrations.RemoveField(
            model_name='nanoinnovation_laboratorysamples',
            name='powder_form',
        ),
        migrations.RemoveField(
            model_name='nanoinnovation_laboratorysamples',
            name='powder_hazard',
        ),
        migrations.RemoveField(
            model_name='nanoinnovation_laboratorysamples',
            name='slice_origin',
        ),
        migrations.RemoveField(
            model_name='nanoinnovation_laboratorysamples',
            name='slice_standing',
        ),
        migrations.RemoveField(
            model_name='nanoinnovation_laboratorysamples',
            name='slice_thickness_um',
        ),
        migrations.RemoveField(
            model_name='nanoinnovation_laboratorysamples',
            name='solid_cas_number',
        ),
        migrations.RemoveField(
            model_name='nanoinnovation_laboratorysamples',
            name='solid_chemical_name',
        ),
        migrations.RemoveField(
            model_name='nanoinnovation_laboratorysamples',
            name='solid_hazard',
        ),
        migrations.RemoveField(
            model_name='nanoinnovation_laboratorysamples',
            name='support_material',
        ),
        migrations.RemoveField(
            model_name='nanoinnovation_laboratorysamples',
            name='support_measures',
        ),
        migrations.RemoveField(
            model_name='nanoinnovation_laboratorysamples',
            name='thin_film_type',
        ),
        migrations.RemoveField(
            model_name='nanoinnovation_laboratorysamples',
            name='virus_family',
        ),
        migrations.AddField(
            model_name='nanoinnovation_laboratorysamples',
            name='bio_safety_level',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='nanoinnovation_laboratorysamples',
            name='chemical_hazard',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='nanoinnovation_laboratorysamples',
            name='chemical_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='nanoinnovation_laboratorysamples',
            name='chemical_name_CAS_list',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AddField(
            model_name='nanoinnovation_laboratorysamples',
            name='culture_medium',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='nanoinnovation_laboratorysamples',
            name='film_thickness',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='nanoinnovation_laboratorysamples',
            name='form',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='nanoinnovation_laboratorysamples',
            name='origin',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='nanoinnovation_laboratorysamples',
            name='other',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='nanoinnovation_laboratorysamples',
            name='pure_or_mixture',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='nanoinnovation_laboratorysamples',
            name='self_standing_or_free_standing',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='nanoinnovation_laboratorysamples',
            name='slice_thickness',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='nanoinnovation_laboratorysamples',
            name='stiffness_and_roughness_ranges',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='nanoinnovation_laboratorysamples',
            name='support',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='nanoinnovation_laboratorysamples',
            name='adherent_or_suspended',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='nanoinnovation_laboratorysamples',
            name='buffer_medium',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='nanoinnovation_laboratorysamples',
            name='embedding_medium',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
