# Generated by Django 5.2.7 on 2025-10-24 13:12

import PRP_CDM_app.models.laboratory_models.mass_spectroscopy_infrastructure
import django.db.models.deletion
from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mass_Spectroscopy_InfrastructureSamples',
            fields=[
                ('samples_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PRP_CDM_app.samples')),
                ('type', models.CharField(blank=True, max_length=255)),
                ('volume_weight', models.CharField(max_length=255)),
                ('biological_replicates', models.CharField(max_length=255)),
                ('solubilized', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True)),
                ('buffer_name', models.CharField(max_length=255)),
                ('sample_date', models.DateField(blank=True, null=True)),
                ('dry_ice', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True)),
                ('cell_counting', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True)),
                ('bradford', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True)),
                ('sample_return', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True)),
                ('results_deadline', models.DateField(blank=True, null=True)),
                ('sample_sheet_filename', models.FileField(blank=True, upload_to=PRP_CDM_app.models.laboratory_models.mass_spectroscopy_infrastructure.Mass_Spectroscopy_InfrastructureSamples.user_directory_path)),
                ('additional_filename', models.FileField(blank=True, upload_to=PRP_CDM_app.models.laboratory_models.mass_spectroscopy_infrastructure.Mass_Spectroscopy_InfrastructureSamples.user_directory_path)),
            ],
            options={
                'db_table': 'msi_samples',
            },
            bases=('PRP_CDM_app.samples',),
        ),
        migrations.RemoveField(
            model_name='proposals',
            name='proposal_date',
        ),
        migrations.RemoveField(
            model_name='proposals',
            name='proposal_feasibility',
        ),
        migrations.RemoveField(
            model_name='proposals',
            name='proposal_status',
        ),
        migrations.AddField(
            model_name='proposals',
            name='scheduled_instrument_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='proposals',
            name='status',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposals',
            name='submission_date',
            field=models.DateTimeField(default=datetime.datetime.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposals',
            name='team_leader',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposals',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proposals',
            name='proposal_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Mass_Spectroscopy_InfrastructureMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata_id', models.CharField(max_length=64, unique=True)),
                ('device_name', models.CharField(blank=True, max_length=255, null=True)),
                ('formatted_voltage', models.CharField(blank=True, max_length=50, null=True)),
                ('exposure_s', models.FloatField(blank=True, null=True)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PRP_CDM_app.samples')),
            ],
        ),
    ]
