# Generated by Django 5.2.4 on 2025-07-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0002_remove_nanoinnovation_laboratorysamples_bacteria_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nanoinnovation_laboratorysamples',
            name='is_fixed',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='nanoinnovation_laboratorysamples',
            name='polishing',
            field=models.CharField(blank=True),
        ),
    ]
