# Generated by Django 5.2.7 on 2025-10-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0002_mass_spectroscopy_infrastructuresamples_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposals',
            name='team_leader',
        ),
        migrations.AddField(
            model_name='proposals',
            name='team_leader_email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposals',
            name='team_leader_first_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposals',
            name='team_leader_last_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposals',
            name='team_leader_username',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
