# Generated by Django 5.2 on 2025-04-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0002_experimentdmp_experimentdmpxinstrument_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentdmp',
            name='article_doi',
        ),
        migrations.RemoveField(
            model_name='experimentdmp',
            name='main_repository',
        ),
        migrations.AddField(
            model_name='experimentdmp',
            name='affiliated_institutions',
            field=models.TextField(default='Area Science Park, Trieste'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experimentdmp',
            name='collaborators_roles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experimentdmp',
            name='estimated_costs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experimentdmp',
            name='ethics_approvals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experimentdmp',
            name='experiment_title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experimentdmp',
            name='funding_programme',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='experimentdmp',
            name='grant_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experimentdmp',
            name='infrastructure_support',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experimentdmp',
            name='plan_creation_date',
            field=models.DateField(default='1970-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experimentdmp',
            name='principal_investigator',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experimentdmp',
            name='project_acronym',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experimentdmp',
            name='roles_responsibilities',
            field=models.TextField(blank=True, null=True),
        ),
    ]
