# Generated by Django 5.2.7 on 2025-10-24 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0003_remove_proposals_team_leader_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samples',
            name='sr_id',
        ),
        migrations.AddField(
            model_name='samples',
            name='proposal_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='PRP_CDM_app.proposals'),
        ),
    ]
