# Generated by Django 5.2 on 2025-04-14 07:15

import PRP_CDM_app.models.laboratory_models.bio_open_lab_unisalento
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0003_remove_experimentdmp_article_doi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio_Open_Lab_UnisalentoSamples',
            fields=[
                ('samples_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PRP_CDM_app.samples')),
                ('sample_name', models.CharField(max_length=255)),
                ('sample_producer', models.CharField(max_length=255)),
                ('affiliation', models.CharField(max_length=255)),
                ('sample_purpose', models.CharField(blank=True)),
                ('sample_type', models.CharField(blank=True)),
                ('component_name', models.CharField(max_length=255)),
                ('component_chemical_formula', models.CharField(max_length=255)),
                ('sheet', models.CharField(blank=True)),
                ('layer', models.CharField(blank=True)),
                ('colloidal_solution', models.CharField(max_length=255)),
                ('sample_expiration_date', models.DateField(blank=True, null=True)),
                ('additional_filename', models.FileField(blank=True, upload_to=PRP_CDM_app.models.laboratory_models.bio_open_lab_unisalento.Bio_Open_Lab_UnisalentoSamples.user_directory_path)),
            ],
            options={
                'db_table': 'bioopenlabunisalento_samples',
            },
            bases=('PRP_CDM_app.samples',),
        ),
    ]
