# Generated by Django 5.2.4 on 2025-07-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0003_nanoinnovation_laboratorysamples_is_fixed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nanoinnovation_laboratorysamples',
            name='adherent_or_suspended',
            field=models.CharField(blank=True, choices=[('adherent', 'Adherent'), ('suspended', 'Suspended')], max_length=64),
        ),
        migrations.AlterField(
            model_name='nanoinnovation_laboratorysamples',
            name='chemical_hazard',
            field=models.CharField(blank=True, choices=[('asphyxiants', 'asphyxiants'), ('corrosives', 'corrosives'), ('irritants', 'irritants'), ('sensitizers', 'sensitizers'), ('carcinogens', 'carcinogens'), ('mutagens', 'mutagens'), ('teratogens', 'teratogens'), ('reactants', 'reactants'), ('flammables', 'flammables')], max_length=64),
        ),
        migrations.AlterField(
            model_name='nanoinnovation_laboratorysamples',
            name='form',
            field=models.CharField(blank=True, choices=[('crystals', 'Crystals'), ('amorphous', 'Amorphous')], max_length=64),
        ),
        migrations.AlterField(
            model_name='nanoinnovation_laboratorysamples',
            name='pure_or_mixture',
            field=models.CharField(blank=True, choices=[('pure', 'Pure'), ('mixture', 'Mixture')], max_length=64),
        ),
        migrations.AlterField(
            model_name='nanoinnovation_laboratorysamples',
            name='self_standing_or_free_standing',
            field=models.CharField(blank=True, choices=[('supported', 'Supported'), ('free', 'Free standing')], max_length=64),
        ),
        migrations.AlterField(
            model_name='nanoinnovation_laboratorysamples',
            name='type',
            field=models.CharField(blank=True, choices=[('animal_tissue', 'Animal/Vegetal Tissue Slides'), ('cultured_cells', 'Cultured Animal Eukaryotic Cells'), ('bacteria', 'Bacteria'), ('virus', 'Virus'), ('powder', 'Powder Sample'), ('thin_film', 'Sample in Thin Films'), ('non_bio_slice', 'Non Biological Slices or Cross-sections'), ('gel', 'Gels'), ('solid', 'Solid Materials')], max_length=64),
        ),
    ]
