# Generated by Django 5.2.4 on 2025-07-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0004_alter_nanoinnovation_laboratorysamples_adherent_or_suspended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nanoinnovation_laboratorysamples',
            name='chemical_name_CAS_list',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='nanoinnovation_laboratorysamples',
            name='other',
            field=models.TextField(blank=True),
        ),
    ]
