# Generated by Django 5.2.1 on 2025-05-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0004_bio_open_lab_unisalentosamples'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentdmp',
            name='instruments',
            field=models.ManyToManyField(through='PRP_CDM_app.ExperimentDMPxInstrument', to='PRP_CDM_app.instruments'),
        ),
        migrations.AddField(
            model_name='experimentdmp',
            name='samples',
            field=models.ManyToManyField(through='PRP_CDM_app.ExperimentDMPxSample', to='PRP_CDM_app.samples'),
        ),
    ]
