# Generated by Django 5.2.7 on 2025-10-28 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0004_remove_samples_sr_id_samples_proposal_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samples',
            old_name='proposal_id',
            new_name='proposal',
        ),
    ]
