# Generated by Django 5.2.1 on 2025-05-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0005_experimentdmp_instruments_experimentdmp_samples'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruments',
            name='labs',
            field=models.ManyToManyField(through='PRP_CDM_app.LabXInstrument', to='PRP_CDM_app.laboratories'),
        ),
    ]
