# Generated by Django 5.2.8 on 2025-11-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0006_sissi_biosamples_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nanoinnovation_laboratorysamples',
            name='type',
            field=models.CharField(blank=True, choices=[('animal_tissue', 'Animal/Vegetal Tissue Slides'), ('cultured_cells', 'Cultured Animal Eukaryotic Cells'), ('bacteria', 'Bacteria'), ('virus', 'Virus'), ('powder', 'Powder Sample'), ('thin_film', 'Sample in Thin Films'), ('non_bio_slice', 'Non Biological Slices or Cross-sections'), ('gel', 'Gels'), ('solid', 'Solid Materials'), ('other', 'other')], max_length=64),
        ),
        migrations.AlterField(
            model_name='sissi_biosamples',
            name='type',
            field=models.CharField(blank=True, choices=[('animal_tissue', 'Animal/Vegetal Tissue Slides'), ('cultured_cells', 'Cultured Animal Eukaryotic Cells'), ('bacteria', 'Bacteria'), ('virus', 'Virus'), ('powder', 'Powder Sample'), ('liquid', 'Liquid'), ('thin_film', 'Sample in Thin Films'), ('embedded', 'Embedded Materials'), ('layered', 'Layered Materials'), ('other', 'other')], max_length=255),
        ),
    ]
