# Generated by Django 5.2.1 on 2025-05-30 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0006_instruments_labs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labxinstrument',
            name='instrument_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instrument_labs', to='PRP_CDM_app.instruments'),
        ),
        migrations.AlterField(
            model_name='labxinstrument',
            name='lab_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_instruments', to='PRP_CDM_app.laboratories'),
        ),
    ]
