# Generated by Django 5.2.8 on 2025-11-13 13:30

import PRP_CDM_app.models.laboratory_models.iuvs
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0007_alter_nanoinnovation_laboratorysamples_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IuvsSamples',
            fields=[
                ('samples_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PRP_CDM_app.samples')),
                ('type', models.CharField(blank=True, choices=[('animal_tissue', 'Animal/Vegetal Tissue Slides'), ('cultured_cells', 'Cultured Animal Eukaryotic Cells'), ('bacteria', 'Bacteria'), ('virus', 'Virus'), ('powder', 'Powder Sample'), ('liquid', 'Liquid'), ('thin_film', 'Sample in Thin Films'), ('embedded', 'Embedded Materials'), ('layered', 'Layered Materials'), ('other', 'other')], max_length=255)),
                ('adherent_or_suspended', models.CharField(blank=True, choices=[('adherent', 'Adherent'), ('suspended', 'Suspended')], max_length=64)),
                ('bio_safety_level', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1)),
                ('buffer_medium', models.CharField(blank=True, max_length=512)),
                ('cas_number', models.CharField(blank=True, max_length=256)),
                ('chemical_hazard', models.CharField(blank=True, choices=[('asphyxiants', 'asphyxiants'), ('corrosives', 'corrosives'), ('irritants', 'irritants'), ('sensitizers', 'sensitizers'), ('carcinogens', 'carcinogens'), ('mutagens', 'mutagens'), ('teratogens', 'teratogens'), ('reactants', 'reactants'), ('flammables', 'flammables')], max_length=64)),
                ('chemical_name', models.CharField(blank=True, max_length=256)),
                ('chemical_name_CAS_list', models.TextField(blank=True)),
                ('culture_medium', models.CharField(blank=True, max_length=256)),
                ('embedding_medium', models.CharField(blank=True, max_length=256)),
                ('stiffness_and_roughness_ranges', models.CharField(blank=True, max_length=256)),
                ('slice_thickness', models.CharField(blank=True, max_length=32)),
                ('film_thickness', models.CharField(blank=True, max_length=32)),
                ('form', models.CharField(blank=True, choices=[('crystals', 'Crystals'), ('amorphous', 'Amorphous')], max_length=64)),
                ('is_fixed', models.CharField(blank=True)),
                ('origin', models.CharField(blank=True, max_length=256)),
                ('other', models.TextField(blank=True)),
                ('polishing', models.CharField(blank=True)),
                ('pure_or_mixture', models.CharField(blank=True, choices=[('pure', 'Pure'), ('mixture', 'Mixture')], max_length=64)),
                ('self_standing_or_free_standing', models.CharField(blank=True, choices=[('supported', 'Supported'), ('free', 'Free standing')], max_length=64)),
                ('support', models.CharField(blank=True, max_length=256)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('sample_sheet_filename', models.FileField(blank=True, upload_to=PRP_CDM_app.models.laboratory_models.iuvs.IuvsSamples.user_directory_path)),
                ('additional_filename', models.FileField(blank=True, upload_to=PRP_CDM_app.models.laboratory_models.iuvs.IuvsSamples.user_directory_path)),
            ],
            options={
                'db_table': 'iuvs_samples',
            },
            bases=('PRP_CDM_app.samples',),
        ),
        migrations.CreateModel(
            name='IuvsMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata_id', models.CharField(max_length=64, unique=True)),
                ('device_name', models.CharField(blank=True, max_length=255, null=True)),
                ('formatted_voltage', models.CharField(blank=True, max_length=50, null=True)),
                ('exposure_s', models.FloatField(blank=True, null=True)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PRP_CDM_app.samples')),
            ],
        ),
    ]
