# Generated by Django 5.2.8 on 2025-11-21 13:46

import PRP_CDM_app.models.laboratory_models.struct_bio_lab
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0008_iuvssamples_iuvsmetadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Struct_Bio_LabSamples',
            fields=[
                ('samples_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PRP_CDM_app.samples')),
                ('type', models.CharField(blank=True, choices=[('cultured_cells', 'Cultured Animal Eukaryotic Cells'), ('bacteria', 'Bacteria'), ('virus', 'Virus'), ('protein', 'Protein'), ('nucleic acid', 'Nucleic Acid'), ('chemical sample', 'Chemical Sample'), ('other', 'other')], max_length=255)),
                ('adherent_or_suspended', models.CharField(blank=True, choices=[('adherent', 'Adherent'), ('suspended', 'Suspended')], max_length=64)),
                ('affiliation', models.CharField(blank=True, max_length=512)),
                ('antibiotic_resistance', models.CharField(blank=True, max_length=512)),
                ('bio_safety_level', models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], max_length=1)),
                ('buffer_medium', models.CharField(blank=True, max_length=512)),
                ('cas_number', models.CharField(blank=True, max_length=256)),
                ('chemical_hazard', models.CharField(blank=True, max_length=256)),
                ('chemical_name', models.CharField(blank=True, max_length=256)),
                ('chemical_name_CAS_list', models.TextField(blank=True)),
                ('culture_medium', models.CharField(blank=True, max_length=256)),
                ('embedding_medium', models.CharField(blank=True, max_length=256)),
                ('microplasma_test', models.CharField(blank=True)),
                ('sample_producer', models.CharField(blank=True, max_length=512)),
                ('sample_purpose', models.CharField(blank=True, max_length=512)),
                ('sample_destination_upon_usage', models.CharField(blank=True, max_length=512)),
                ('stiffness_and_roughness_ranges', models.CharField(blank=True, max_length=256)),
                ('slice_thickness', models.CharField(blank=True, max_length=32)),
                ('storage', models.CharField(blank=True, choices=[('RT', 'Room Temperature'), ('4C', '4 °C'), ('-20C', '-20 °C'), ('-80C', '-80 °C'), ('nitrogen', 'Liquid Nitrogen')], max_length=10)),
                ('transformed_with_vector', models.CharField(blank=True)),
                ('film_thickness', models.CharField(blank=True, max_length=32)),
                ('is_fixed', models.CharField(blank=True)),
                ('origin', models.CharField(blank=True, max_length=256)),
                ('other', models.TextField(blank=True)),
                ('polishing', models.CharField(blank=True)),
                ('pure_or_mixture', models.CharField(blank=True, choices=[('pure', 'Pure'), ('mixture', 'Mixture')], max_length=64)),
                ('support', models.CharField(blank=True, max_length=256)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('sample_sheet_filename', models.FileField(blank=True, upload_to=PRP_CDM_app.models.laboratory_models.struct_bio_lab.Struct_Bio_LabSamples.user_directory_path)),
                ('additional_filename', models.FileField(blank=True, upload_to=PRP_CDM_app.models.laboratory_models.struct_bio_lab.Struct_Bio_LabSamples.user_directory_path)),
            ],
            options={
                'db_table': 'struct_bio_lab_samples',
            },
            bases=('PRP_CDM_app.samples',),
        ),
        migrations.CreateModel(
            name='Struct_Bio_LabMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata_id', models.CharField(max_length=64, unique=True)),
                ('device_name', models.CharField(blank=True, max_length=255, null=True)),
                ('formatted_voltage', models.CharField(blank=True, max_length=50, null=True)),
                ('exposure_s', models.FloatField(blank=True, null=True)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PRP_CDM_app.samples')),
            ],
        ),
    ]
