# Generated by Django 5.2.8 on 2025-11-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0009_struct_bio_labsamples_struct_bio_labmetadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='struct_bio_labsamples',
            name='microplasma_test',
        ),
        migrations.AddField(
            model_name='struct_bio_labsamples',
            name='mycoplasma_test',
            field=models.CharField(blank=True),
        ),
    ]
