# Generated by Django 5.2.1 on 2025-06-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0010_alter_experimentdmp_instruments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentdmp',
            name='instruments',
            field=models.ManyToManyField(through='PRP_CDM_app.ExperimentDMPxInstrument', to='PRP_CDM_app.instruments'),
        ),
        migrations.AlterField(
            model_name='experimentdmp',
            name='samples',
            field=models.ManyToManyField(through='PRP_CDM_app.ExperimentDMPxSample', to='PRP_CDM_app.samples'),
        ),
    ]
