# Generated by Django 5.2.8 on 2025-11-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0010_remove_struct_bio_labsamples_microplasma_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='struct_bio_labsamples',
            name='mycoplasma_test',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
    ]
