# Generated by Django 5.2.8 on 2025-11-21 15:59

import PRP_CDM_app.models.laboratory_models.struct_bio_lab
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0011_alter_struct_bio_labsamples_mycoplasma_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='struct_bio_labsamples',
            name='genebank_id',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='struct_bio_labsamples',
            name='name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='struct_bio_labsamples',
            name='sequence',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='struct_bio_labsamples',
            name='sequence_file',
            field=models.FileField(blank=True, null=True, upload_to=PRP_CDM_app.models.laboratory_models.struct_bio_lab.Struct_Bio_LabSamples.user_directory_path),
        ),
    ]
