# Generated by Django 5.2.1 on 2025-06-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0011_alter_experimentdmp_instruments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentdmp',
            name='lab',
            field=models.ManyToManyField(through='PRP_CDM_app.ExperimentDMPxLab', to='PRP_CDM_app.laboratories'),
        ),
    ]
