# Generated by Django 5.2.8 on 2025-11-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0012_struct_bio_labsamples_genebank_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='struct_bio_labsamples',
            name='molar_weight',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='struct_bio_labsamples',
            name='quality_control',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='struct_bio_labsamples',
            name='quantity_concentration_medium',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='struct_bio_labsamples',
            name='recombinant',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='struct_bio_labsamples',
            name='recombinant_source',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
