# Generated by Django 5.2.8 on 2025-11-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0013_struct_bio_labsamples_molar_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='struct_bio_labsamples',
            name='quantity_concentration_medium',
        ),
        migrations.AddField(
            model_name='struct_bio_labsamples',
            name='quantity_concentration_buffer',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
