# Generated by Django 5.2.2 on 2025-06-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0014_alter_resultxexperimentdmp_experiment_dmp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio_Open_Lab_UnisalentoMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(blank=True, max_length=255, null=True)),
                ('formatted_voltage', models.CharField(blank=True, max_length=50, null=True)),
                ('exposure_s', models.FloatField(blank=True, null=True)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('acquisition_time', models.FloatField(blank=True, null=True)),
                ('formatted_indicated_mag', models.CharField(blank=True, max_length=50, null=True)),
                ('pixel_size_um', models.JSONField(blank=True, null=True)),
                ('pixel_depth', models.IntegerField(blank=True, null=True)),
                ('stage_alpha', models.CharField(blank=True, max_length=50, null=True)),
                ('stage_beta', models.CharField(blank=True, max_length=50, null=True)),
                ('stage_x', models.CharField(blank=True, max_length=50, null=True)),
                ('stage_y', models.CharField(blank=True, max_length=50, null=True)),
                ('stage_z', models.CharField(blank=True, max_length=50, null=True)),
                ('active_size_pixels', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
