# Generated by Django 5.2.8 on 2025-11-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0014_remove_struct_bio_labsamples_quantity_concentration_medium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='struct_bio_labsamples',
            name='type',
            field=models.CharField(blank=True, choices=[('cultured_cells', 'Cultured Animal Eukaryotic Cells'), ('bacteria', 'Bacteria'), ('virus', 'Virus'), ('protein', 'Protein'), ('nucleic_acid', 'Nucleic Acid'), ('chemical sample', 'Chemical Sample'), ('other', 'other')], max_length=255),
        ),
    ]
