# Generated by Django 5.2.8 on 2025-11-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0015_alter_struct_bio_labsamples_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='struct_bio_labsamples',
            name='form',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='struct_bio_labsamples',
            name='type_nucleic',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
