# Generated by Django 5.2.2 on 2025-06-07 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0015_bio_open_lab_unisalentometadata'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bio_open_lab_unisalentometadata',
            table='bio_open_lab_unisalentometadata',
        ),
    ]
