# Generated by Django 5.2.8 on 2025-11-24 10:37

import PRP_CDM_app.models.laboratory_models.struct_bio_lab
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0016_struct_bio_labsamples_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='struct_bio_labsamples',
            name='vector_file',
            field=models.FileField(blank=True, null=True, upload_to=PRP_CDM_app.models.laboratory_models.struct_bio_lab.Struct_Bio_LabSamples.user_directory_path),
        ),
    ]
