# Generated by Django 5.2.8 on 2025-11-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0017_struct_bio_labsamples_vector_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='struct_bio_labsamples',
            name='structure',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='struct_bio_labsamples',
            name='type',
            field=models.CharField(blank=True, choices=[('cultured_cells', 'Cultured Animal Eukaryotic Cells'), ('bacteria', 'Bacteria'), ('virus', 'Virus'), ('protein', 'Protein'), ('nucleic_acid', 'Nucleic Acid'), ('chemical_sample', 'Chemical Sample'), ('other', 'other')], max_length=255),
        ),
    ]
