# Generated by Django 5.2.2 on 2025-06-07 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0017_bio_open_lab_unisalentometadata_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio_open_lab_unisalentometadata',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PRP_CDM_app.samples'),
        ),
    ]
