# Generated by Django 5.2.2 on 2025-06-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0018_alter_bio_open_lab_unisalentometadata_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio_open_lab_unisalentometadata',
            name='metadata_id',
            field=models.CharField(default='', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
