# Generated by Django 5.2.8 on 2025-12-01 10:32

import PRP_CDM_app.models.laboratory_models.cnr_ic
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0018_struct_bio_labsamples_structure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cnr_IcSamples',
            fields=[
                ('samples_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PRP_CDM_app.samples')),
                ('type', models.CharField(blank=True, choices=[('protein', 'Protein'), ('dna', 'DNA'), ('rna', 'RNA'), ('peptides', 'Peptides'), ('small_molecule', 'Small Molecule')], max_length=255)),
                ('assay_temperature', models.CharField(blank=True, max_length=55)),
                ('buffer', models.CharField(blank=True, max_length=255)),
                ('concentration', models.CharField(blank=True, max_length=25)),
                ('isoelectric_point', models.CharField(blank=True, max_length=25)),
                ('kd_technique', models.CharField(blank=True, max_length=255)),
                ('ligand', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=255)),
                ('molecular_weight', models.CharField(blank=True, max_length=55)),
                ('running_buffer', models.CharField(blank=True, max_length=255)),
                ('solubility', models.CharField(blank=True, max_length=55)),
                ('storage', models.CharField(blank=True, choices=[('RT', 'Room Temperature'), ('4C', '4 °C'), ('-20C', '-20 °C'), ('-80C', '-80 °C'), ('nitrogen', 'Liquid Nitrogen')], max_length=10)),
                ('target', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=255)),
                ('tag', models.CharField(blank=True, max_length=255)),
                ('sample_sheet_filename', models.FileField(blank=True, upload_to=PRP_CDM_app.models.laboratory_models.cnr_ic.Cnr_IcSamples.user_directory_path)),
                ('additional_filename', models.FileField(blank=True, upload_to=PRP_CDM_app.models.laboratory_models.cnr_ic.Cnr_IcSamples.user_directory_path)),
            ],
            options={
                'db_table': 'cnr_ic_samples',
            },
            bases=('PRP_CDM_app.samples',),
        ),
        migrations.CreateModel(
            name='Cnr_IcMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata_id', models.CharField(max_length=64, unique=True)),
                ('device_name', models.CharField(blank=True, max_length=255, null=True)),
                ('formatted_voltage', models.CharField(blank=True, max_length=50, null=True)),
                ('exposure_s', models.FloatField(blank=True, null=True)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PRP_CDM_app.samples')),
            ],
        ),
    ]
