# Generated by Django 5.2.2 on 2025-06-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0019_bio_open_lab_unisalentometadata_metadata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio_open_lab_unisalentometadata',
            name='metadata_id',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
