# Generated by Django 5.2.8 on 2025-12-01 13:31

import PRP_CDM_app.models.laboratory_models.cnr_iom
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0019_cnr_icsamples_cnr_icmetadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cnr_IomSamples',
            fields=[
                ('samples_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PRP_CDM_app.samples')),
                ('biological_material_description', models.CharField(blank=True, max_length=255)),
                ('expression_methods', models.CharField(blank=True, max_length=255)),
                ('buffering', models.CharField(blank=True, max_length=255)),
                ('concentration', models.CharField(blank=True, max_length=255)),
                ('grid_type', models.CharField(blank=True, max_length=255)),
                ('molecular_weight', models.CharField(blank=True, max_length=255)),
                ('fixation_method', models.CharField(blank=True, max_length=255)),
                ('labelling_method_category', models.CharField(blank=True, max_length=255)),
                ('labelling_method_dyes', models.CharField(blank=True, max_length=255)),
                ('immunolabelling_method', models.CharField(blank=True, max_length=255)),
                ('labelling_method_probe', models.CharField(blank=True, max_length=255)),
                ('organization', models.CharField(blank=True, max_length=85)),
                ('purification_stabilization', models.CharField(blank=True, max_length=255)),
                ('purpose', models.CharField(blank=True, choices=[('screening', 'Screening'), ('sample_optimization', 'Sample Optimization'), ('data_collection', 'Data Collection'), ('celular_tomography', 'Cellular Tomography'), ('cryo_fib', 'Cryo-FIB')], max_length=55)),
                ('sample_acronym', models.CharField(blank=True, max_length=255)),
                ('sample_name', models.CharField(blank=True, max_length=255)),
                ('sequence', models.CharField(blank=True, max_length=255)),
                ('substrate_treatement', models.CharField(blank=True, max_length=255)),
                ('sample_sheet_filename', models.FileField(blank=True, upload_to=PRP_CDM_app.models.laboratory_models.cnr_iom.Cnr_IomSamples.user_directory_path)),
                ('additional_filename', models.FileField(blank=True, upload_to=PRP_CDM_app.models.laboratory_models.cnr_iom.Cnr_IomSamples.user_directory_path)),
                ('sequence_file', models.FileField(blank=True, null=True, upload_to=PRP_CDM_app.models.laboratory_models.cnr_iom.Cnr_IomSamples.user_directory_path)),
            ],
            options={
                'db_table': 'cnr_iom_samples',
            },
            bases=('PRP_CDM_app.samples',),
        ),
    ]
