# Generated by Django 5.2.2 on 2025-06-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0020_alter_bio_open_lab_unisalentometadata_metadata_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labdmp',
            name='clear_data_provenance',
        ),
        migrations.RemoveField(
            model_name='labdmp',
            name='licence_scientific_documents',
        ),
        migrations.RemoveField(
            model_name='labdmp',
            name='open_access_journal_publication',
        ),
        migrations.RemoveField(
            model_name='labdmp',
            name='open_data_licence',
        ),
        migrations.RemoveField(
            model_name='labdmp',
            name='open_trusted_repo_published_data',
        ),
        migrations.RemoveField(
            model_name='labdmp',
            name='raw_data_storage_location',
        ),
        migrations.RemoveField(
            model_name='labdmp',
            name='raw_data_storage_time_retention',
        ),
        migrations.RemoveField(
            model_name='labdmp',
            name='related_data_open',
        ),
        migrations.AddField(
            model_name='labdmp',
            name='data_curator',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='results',
            name='clear_data_provenance',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='results',
            name='licence_scientific_documents',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='results',
            name='open_access_journal_publication',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='results',
            name='open_data_licence',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='results',
            name='open_trusted_repo_published_data',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='results',
            name='raw_data_storage_location',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='results',
            name='raw_data_storage_time_retention',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='results',
            name='related_data_open',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samples',
            name='sensible_data',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
    ]
