# Generated by Django 6.0.2 on 2026-02-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0021_bio_open_lab_unisalentosamples_submitted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposals',
            name='team_members',
            field=models.JSONField(default=list),
        ),
    ]
