# Generated by Django 6.0 on 2025-12-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0021_alter_nanoinnovation_laboratorysamples_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nanoinnovation_laboratorysamples',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
