# Generated by Django 6.0 on 2025-12-16 13:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0025_bio_open_lab_unisalentometadata_submitted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mass_spectroscopy_infrastructuresamples',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
