# Generated by Django 6.0 on 2025-12-16 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0025_bio_open_lab_unisalentometadata_submitted_at_and_more'),
    ]

    operations = [
    ]
