# Generated by Django 6.0 on 2025-12-16 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0026_mass_spectroscopy_infrastructuresamples_submitted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bio_open_lab_unisalentometadata',
            name='submitted_at',
        ),
    ]
