# Generated by Django 6.0.2 on 2026-02-23 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0022_proposals_team_members'),
        ('PRP_CDM_app', '0027_remove_bio_open_lab_unisalentometadata_submitted_at_and_more'),
    ]

    operations = [
    ]
