# Generated by Django 6.0.2 on 2026-02-26 16:17

import PRP_CDM_app.models.laboratory_models.functional_screening_facility
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0029_biosafety_facilitysamples'),
    ]

    operations = [
        migrations.CreateModel(
            name='Functional_Screening_FacilitySamples',
            fields=[
                ('samples_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PRP_CDM_app.samples')),
                ('type', models.CharField(blank=True, max_length=255)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bio_safety_level', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1)),
                ('buffer_medium', models.CharField(blank=True, max_length=512)),
                ('concentration', models.CharField(blank=True, max_length=255)),
                ('other', models.TextField(blank=True)),
                ('sample_producer', models.CharField(blank=True, max_length=255)),
                ('volume', models.CharField(blank=True, max_length=255)),
                ('sample_sheet_filename', models.FileField(blank=True, upload_to=PRP_CDM_app.models.laboratory_models.functional_screening_facility.Functional_Screening_FacilitySamples.user_directory_path)),
                ('additional_filename', models.FileField(blank=True, upload_to=PRP_CDM_app.models.laboratory_models.functional_screening_facility.Functional_Screening_FacilitySamples.user_directory_path)),
            ],
            options={
                'db_table': 'functional_screening_facility_samples',
            },
            bases=('PRP_CDM_app.samples',),
        ),
    ]
