# Generated by Django 5.1.6 on 2025-02-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API_Tokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField()),
                ('laboratory', models.CharField()),
                ('elab_token', models.CharField(blank=True, max_length=128, null=True)),
                ('jenkins_token', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'api_tokens',
            },
        ),
    ]
