# Generated by Django 5.2 on 2025-04-08 13:58

import PRP_CDM_app.models.laboratory_models.bio_open_lab_unisalento
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio_Open_Lab_Unisalento',
            fields=[
                ('samples_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PRP_CDM_app.samples')),
                ('chemical_formula', models.CharField(blank=True)),
                ('elements_list', models.CharField(blank=True)),
                ('sample_date_of_delivery', models.DateField()),
                ('sample_back', models.BooleanField()),
                ('sample_sheet_filename', models.FileField(blank=True, upload_to=PRP_CDM_app.models.laboratory_models.bio_open_lab_unisalento.Bio_Open_Lab_Unisalento.user_directory_path)),
                ('additional_filename', models.FileField(blank=True, upload_to=PRP_CDM_app.models.laboratory_models.bio_open_lab_unisalento.Bio_Open_Lab_Unisalento.user_directory_path)),
            ],
            options={
                'db_table': 'bio_open_lab_unisalento',
            },
            bases=('PRP_CDM_app.samples',),
        ),
    ]
