# Generated by Django 5.1.6 on 2025-03-06 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentDataManagementPlan',
            fields=[
                ('experiment_dmp_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='FilesInfo',
            fields=[
                ('file_info_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('extension', models.CharField(max_length=128)),
                ('is_open', models.BooleanField(default=False)),
                ('software_used', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'db_table': 'filesinfo',
            },
        ),
        migrations.CreateModel(
            name='ExperimentDMPxInstrument',
            fields=[
                ('x_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('experimentdmp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PRP_CDM_app.experimentdatamanagementplan')),
                ('instruments', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PRP_CDM_app.instruments')),
            ],
            options={
                'db_table': 'experimentdmp_x_instrument',
            },
        ),
        migrations.CreateModel(
            name='ExperimentDMPxLab',
            fields=[
                ('x_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('experimentdmp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PRP_CDM_app.experimentdatamanagementplan')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PRP_CDM_app.laboratories')),
            ],
            options={
                'db_table': 'experimentdmp_x_lab',
            },
        ),
        migrations.CreateModel(
            name='ExperimentDMPxSample',
            fields=[
                ('x_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('experimentdmp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PRP_CDM_app.experimentdatamanagementplan')),
                ('samples', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PRP_CDM_app.samples')),
            ],
            options={
                'db_table': 'experimentdmp_x_sample',
            },
        ),
        migrations.CreateModel(
            name='ExperimentDMPxFilesInfo',
            fields=[
                ('x_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('experimentdmp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PRP_CDM_app.experimentdatamanagementplan')),
                ('file_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PRP_CDM_app.filesinfo')),
            ],
            options={
                'db_table': 'experimentdmp_x_filesinfo',
            },
        ),
    ]
