# Generated by Django 5.1.5 on 2025-01-30 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRP_CDM_app', '0004_remove_results_lab_resultxlab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultxsample',
            name='samples',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PRP_CDM_app.samples'),
        ),
    ]
