# Generated by Django 5.1.7 on 2025-04-10 13:21

import django.db.models.deletion
import home.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_newtestpage'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentDMPPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('thankyou_page_title', models.CharField(help_text='Title text shown after experiment DMP submission', max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', home.models.SessionHandlerMixin),
        ),
    ]
