# Generated by Django 5.2.4 on 2025-07-31 11:33

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_samplereportpage'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultReportPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RenameModel(
            old_name='ExperimentMetadataReportPage',
            new_name='EditExperimentDMPPage',
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='footer_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Text displayed in the website footer', verbose_name='Footer Text'),
        ),
    ]
