# Generated by Django 5.2.1 on 2025-06-04 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_samplereportpage'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExperimentMetadataReportPage',
            new_name='ResultReportPage',
        ),
    ]
