# Generated by Django 5.2.1 on 2025-06-04 11:03

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_experimentmetadatareportpage_resultreportpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersettings',
            name='footer_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Text displayed in the website footer', verbose_name='Footer Text'),
        ),
    ]
