# Generated by Django 5.2.7 on 2025-10-24 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_resultreportpage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceRequestSubmissionPage',
        ),
    ]
